# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM openresty/openresty:1.17.8.2-5-alpine-fat

ARG SW_AGENT_NGINX_LUA_COMMIT

WORKDIR /usr/share/skywalking-nginx-lua

ADD https://github.com/apache/skywalking-nginx-lua/archive/${SW_AGENT_NGINX_LUA_COMMIT}.tar.gz .

RUN tar -xf ${SW_AGENT_NGINX_LUA_COMMIT}.tar.gz --strip 1

RUN rm ${SW_AGENT_NGINX_LUA_COMMIT}.tar.gz

RUN luarocks make --only-server https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/daab2726276e3282dc347b89a42a5107c3500567 rockspec/skywalking-nginx-lua-master-0.rockspec

