package com.ai.cloud.skywalking.sample.mybatis.dao;


import java.util.List;

import com.ai.cloud.skywalking.sample.mybatis.model.Sampletable2;
import com.ai.cloud.skywalking.sample.mybatis.model.Sampletable2Example;
import org.apache.ibatis.annotations.Param;

public interface Sampletable2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int countByExample(Sampletable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int deleteByExample(Sampletable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int deleteByPrimaryKey(String key2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int insert(Sampletable2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int insertSelective(Sampletable2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    List<Sampletable2> selectByExample(Sampletable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    Sampletable2 selectByPrimaryKey(String key2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") Sampletable2 record, @Param("example") Sampletable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int updateByExample(@Param("record") Sampletable2 record, @Param("example") Sampletable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int updateByPrimaryKeySelective(Sampletable2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE2
     *
     * @mbggenerated Sun Jul 24 09:26:38 CST 2016
     */
    int updateByPrimaryKey(Sampletable2 record);
}