package com.ai.cloud.skywalking.sample.mybatis.dao;


import com.ai.cloud.skywalking.sample.mybatis.model.Sampletable1;
import com.ai.cloud.skywalking.sample.mybatis.model.Sampletable1Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Sampletable1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int countByExample(Sampletable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int deleteByExample(Sampletable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int deleteByPrimaryKey(String key1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int insert(Sampletable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int insertSelective(Sampletable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    List<Sampletable1> selectByExample(Sampletable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    Sampletable1 selectByPrimaryKey(String key1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") Sampletable1 record, @Param("example") Sampletable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int updateByExample(@Param("record") Sampletable1 record, @Param("example") Sampletable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int updateByPrimaryKeySelective(Sampletable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SAMPLETABLE1
     *
     * @mbggenerated Sun Jul 24 09:19:30 CST 2016
     */
    int updateByPrimaryKey(Sampletable1 record);
}