/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.apache.skywalking.oap.server.admin.dsl.debugging.module;

import lombok.Getter;
import lombok.Setter;
import org.apache.skywalking.oap.server.library.module.ModuleConfig;

/**
 * Per-feature knobs for the DSL debug API. Phase 0c only declares the
 * permanent capture-disable switch; session caps and per-DSL knobs land
 * with the capture phases that depend on them, so the application.yml
 * surface grows incrementally instead of declaring keys whose enforcement
 * code does not yet exist.
 */
@Getter
@Setter
public class DSLDebuggingModuleConfig extends ModuleConfig {
    /**
     * Boot-time switch that enables capture-probe emission in the
     * MAL / LAL / OAL code generators. Default {@code true} — when an operator
     * has explicitly enabled the {@code dsl-debugging} module
     * ({@code SW_DSL_DEBUGGING=default}), they expect probes to be active so
     * that {@code POST /dsl-debugging/session} actually captures samples; this
     * flag exists as a defensive override for the rare case where an operator
     * wants the REST surface (status / sessions list / OAL rule picker) but
     * absolutely no codegen-side probe overhead.
     *
     * <p>The whole {@code dsl-debugging} module is itself disabled by default
     * via the {@code SW_DSL_DEBUGGING} selector, so flipping THIS knob to
     * {@code true} only matters once the module has been turned on.
     *
     * <p>With this flag {@code false}, the generated bytecode is byte-identical
     * to a build without SWIP-13 — an active session would never receive any
     * record because no probe call site exists. Flipping the flag requires an
     * OAP restart (runtime-rule hot-update only refreshes rule content, not
     * codegen flags).
     */
    private boolean injectionEnabled = true;
}
