/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.apache.skywalking.oap.server.receiver.runtimerule.apply;

import java.io.StringReader;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import javassist.ClassPool;
import javassist.LoaderClassPath;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.apache.skywalking.oap.meter.analyzer.v2.MetricConvert;
import org.apache.skywalking.oap.meter.analyzer.v2.prometheus.rule.MetricsRule;
import org.apache.skywalking.oap.meter.analyzer.v2.prometheus.rule.Rule;
import org.apache.skywalking.oap.server.core.CoreModule;
import org.apache.skywalking.oap.server.core.analysis.meter.MeterSystem;
import org.apache.skywalking.oap.server.core.classloader.Catalog;
import org.apache.skywalking.oap.server.core.classloader.DSLClassLoaderManager;
import org.apache.skywalking.oap.server.core.classloader.RuleClassLoader;
import org.apache.skywalking.oap.server.core.storage.model.StorageManipulationOpt;
import org.apache.skywalking.oap.server.library.module.ModuleManager;
import org.apache.skywalking.oap.server.receiver.runtimerule.state.EngineApplied;
import org.yaml.snakeyaml.Yaml;

/**
 * Turns a runtime-rule MAL file (one of the {@code otel-rules} / {@code log-mal-rules}
 * catalogs) into a live {@link MetricConvert} on this OAP node.
 *
 * <p>This is the MAL half of the apply pipeline: parse the stored YAML, construct a
 * {@link MetricConvert}, and let the existing meter-analyzer path register each declared
 * metric name via {@link MeterSystem#create}. Removal reverses the registrations through
 * {@link MeterSystem#removeMetric}, which drains L1/L2 handlers and drops the BanyanDB
 * measure per the work done in bundle A.
 *
 * <p>Class isolation: every MAL-generated class for this file — storage-side {@code Metrics}
 * subclasses (×3 downsampling variants per declared metric), the {@code MalExpression}
 * implementation class per rule, each closure companion, and the {@code MalFilter} if the
 * YAML declares a top-level {@code filter:} — is defined in the per-file
 * {@link RuleClassLoader} created here. Retiring the loader through the dslManager's
 * {@code ClassLoaderGc} on unregister makes the whole bundle GC-eligible at once,
 * observable via the loader's phantom-reference queue.
 */
@Slf4j
public class MalFileApplier {

    private final MeterSystem meterSystem;

    public MalFileApplier(final MeterSystem meterSystem) {
        this.meterSystem = meterSystem;
    }

    /**
     * Parse + compile + register every rule declared in the YAML content.
     *
     * @param yamlContent raw YAML bytes of the rule file (byte-identical to the POSTed body)
     * @param sourceName  informational identifier used in Javassist's {@code SourceFile}
     *                    attribute so generated bytecode shows the originating rule file in
     *                    stack traces. Convention: {@code catalog + "/" + name}.
     * @return {@link Applied} bundle holding the set of metric names this file registered
     *         (used on the next update/delete to call {@link MeterSystem#removeMetric} on
     *         each) plus the {@link MetricConvert}, retained so sample dispatch can reach it.
     * @throws ApplyException on YAML parse error or rule validation failure. MAL expression
     *         compile errors may surface at {@link MetricConvert} construction — those are
     *         also wrapped here so the caller's error handling is uniform.
     */
    public Applied apply(final String yamlContent, final String sourceName,
                         final String contentHash,
                         final StorageManipulationOpt storageOpt) throws ApplyException {
        return apply(yamlContent, sourceName, contentHash, storageOpt,
            DSLClassLoaderManager.Kind.RUNTIME);
    }

    /**
     * Origin-tagged overload: {@link DSLClassLoaderManager.Kind#STATIC} mints a {@code static:}
     * loader so the static fall-over path (bundled rule serving again after the runtime
     * override is removed) is distinguishable from the runtime path in logs and diagnostics.
     */
    public Applied apply(final String yamlContent, final String sourceName,
                         final String contentHash,
                         final StorageManipulationOpt storageOpt,
                         final DSLClassLoaderManager.Kind kind) throws ApplyException {
        final Rule rule = parse(yamlContent, sourceName);
        final Set<String> metricNames = enumerateMetricNames(rule);

        // Per-file RuleClassLoader + Javassist ClassPool. The pool is parented to the default
        // pool so shipped ancestor classes (SumFunction, HistogramFunction, ...) resolve via
        // parent-first lookup; LoaderClassPath ensures Javassist's generator can write the
        // new Metrics subclass into THIS loader. Dropping the bundle drops the loader, and
        // every class the loader defined becomes GC-eligible — observable via the manager's
        // internal phantom-reference queue.
        final int firstSlash = sourceName.indexOf('/');
        final Catalog catalog = firstSlash > 0
            ? Catalog.of(sourceName.substring(0, firstSlash))
            : Catalog.OTEL_RULES;
        final String ruleName = firstSlash > 0
            ? sourceName.substring(firstSlash + 1)
            : sourceName;
        final RuleClassLoader ruleLoader = DSLClassLoaderManager.INSTANCE.newBuilder(
            catalog, ruleName, kind, contentHash);
        final ClassPool pool = new ClassPool(ClassPool.getDefault());
        pool.appendClassPath(new LoaderClassPath(ruleLoader));

        final MetricConvert convert;
        try {
            convert = new MetricConvert(rule, meterSystem, pool, ruleLoader, storageOpt);
        } catch (final MetricConvert.PartialRegistrationException pre) {
            // Phase-2 register threw partway. Carry ONLY the subset that actually landed in
            // MeterSystem — the caller uses this set for rollback. Passing the full enumerated
            // set here would remove metrics the old bundle still owns (disastrous on
            // FILTER_ONLY edits, where by definition every metric name is also in the old
            // bundle).
            throw new ApplyException(
                "MAL register failed for " + sourceName + " (partial)",
                pre.getCause() == null ? pre : pre.getCause(),
                pre.getRegisteredBeforeFailure());
        } catch (final Throwable t) {
            // Phase-1 compile failure or other pre-register throw. Nothing was registered with
            // MeterSystem, so rollback set is empty — passing a non-empty set would cause the
            // caller to unregister metrics the old bundle owns and this apply never touched.
            throw new ApplyException("MAL compile failed for " + sourceName, t, Collections.emptySet());
        }
        return new Applied(rule, convert, metricNames, ruleLoader);
    }

    /**
     * Back-compat overload: callers that haven't yet picked a storage policy pass
     * {@link StorageManipulationOpt#fullInstall()}. Main-node apply path.
     */
    public Applied apply(final String yamlContent, final String sourceName,
                         final String contentHash) throws ApplyException {
        return apply(yamlContent, sourceName, contentHash, StorageManipulationOpt.fullInstall());
    }

    /**
     * Back-compat overload for callers that haven't yet threaded the content hash through.
     * Uses an empty hash — the per-file loader still works, it's just less traceable in the
     * {@code ClassLoaderGc} output.
     */
    public Applied apply(final String yamlContent, final String sourceName) throws ApplyException {
        return apply(yamlContent, sourceName, "", StorageManipulationOpt.fullInstall());
    }

    /**
     * Reverse of {@link #apply}: drop every metric name the previous apply registered under
     * the given {@link StorageManipulationOpt storage policy}. Main-node callers pass
     * {@link StorageManipulationOpt#fullInstall()} so {@code BanyanDBIndexInstaller.dropTable}
     * actually deletes the server-side measure. Peer-node callers pass
     * {@link StorageManipulationOpt#localCacheOnly()} so local teardown (L1/L2 drain,
     * {@code meterPrototypes} eviction, CtClass detach) still runs but the server-side drop
     * is suppressed — main owns server-side state.
     *
     * <p>Failure handling is best-effort-with-surfacing: the loop does NOT abort on the first
     * failing metric (the caller's desired end-state is "all gone", and one stubborn metric
     * should not block the teardown of its siblings), but collected failures throw
     * {@link RemoveException} after the loop. Callers on the REST sync path propagate that
     * throw so the operator sees 500 {@code teardown_deferred} / {@code commit_deferred}
     * instead of a misleading 200 {@code inactivated} / {@code structural_applied}; the
     * dslManager tick wraps the call site so one failing rule doesn't block the whole tick.
     *
     * @throws RemoveException when one or more metrics failed to remove fully. The caller's
     *         local state (this applier's view) has still advanced — MeterSystem's
     *         meterPrototypes entry was dropped on best-effort — but the backend drop (or
     *         worker drain, or CtClass detach) did not fully succeed for the listed names.
     */
    public void remove(final Set<String> metricNames, final StorageManipulationOpt storageOpt) {
        if (metricNames == null || metricNames.isEmpty()) {
            return;
        }
        Map<String, Throwable> failures = null;
        for (final String name : metricNames) {
            try {
                meterSystem.removeMetric(name, storageOpt);
            } catch (final Throwable t) {
                log.warn("runtime-rule MAL remove: failed to remove metric {}", name, t);
                if (failures == null) {
                    failures = new LinkedHashMap<>();
                }
                failures.put(name, t);
            }
        }
        if (failures != null) {
            throw new RemoveException(failures);
        }
    }

    /** Back-compat overload: full-install policy (server-side drop fires). */
    public void remove(final Set<String> metricNames) {
        remove(metricNames, StorageManipulationOpt.fullInstall());
    }

    private Rule parse(final String yamlContent, final String sourceName) throws ApplyException {
        try (StringReader reader = new StringReader(yamlContent)) {
            final Rule rule = new Yaml().loadAs(reader, Rule.class);
            if (rule == null) {
                throw new ApplyException("YAML parsed to null — empty or malformed rule file: "
                    + sourceName, null, Collections.emptySet());
            }
            if (rule.getName() == null || rule.getName().isEmpty()) {
                rule.setName(sourceName);
            }
            return rule;
        } catch (final ApplyException e) {
            throw e;
        } catch (final Throwable t) {
            throw new ApplyException("YAML parse failure for " + sourceName, t, Collections.emptySet());
        }
    }

    /**
     * Parse raw YAML and return the set of metric names the rule file would register.
     * Static-only variant — does not compile, does not register, does not construct a
     * per-file classloader. Used by the dslManager's teardown path when it needs to know
     * which metrics a boot-loaded static rule owns but has no {@link Applied} in
     * {@code appliedMal} to consult (first operator {@code /inactivate} or first
     * structural {@code /addOrUpdate} of a rule that only had a static version).
     *
     * <p>Returns an empty set on any parse failure — teardown is best-effort, and a
     * malformed static rule cannot own live metrics anyway.
     */
    public static Set<String> parseMetricNames(final String yamlContent, final String sourceName) {
        if (yamlContent == null || yamlContent.isEmpty()) {
            return Collections.emptySet();
        }
        try (StringReader reader = new StringReader(yamlContent)) {
            final Rule rule = new Yaml().loadAs(reader, Rule.class);
            if (rule == null) {
                return Collections.emptySet();
            }
            if (rule.getName() == null || rule.getName().isEmpty()) {
                rule.setName(sourceName);
            }
            return enumerateMetricNames(rule);
        } catch (final Throwable t) {
            log.warn("runtime-rule: failed to parse static MAL content for {} — no metric "
                + "names enumerated for teardown", sourceName, t);
            return Collections.emptySet();
        }
    }

    /**
     * Compute the full set of registered metric names for a parsed Rule, mirroring
     * {@code MetricConvert.formatMetricName} ({@code metricPrefix + "_" + ruleName}).
     */
    private static Set<String> enumerateMetricNames(final Rule rule) {
        final Set<String> out = new LinkedHashSet<>();
        if (rule.getMetricsRules() == null) {
            return Collections.unmodifiableSet(out);
        }
        for (final MetricsRule r : rule.getMetricsRules()) {
            if (r.getName() == null) {
                continue;
            }
            out.add(rule.getMetricPrefix() + "_" + r.getName());
        }
        return Collections.unmodifiableSet(out);
    }

    /** Result of a successful {@link #apply} — retained so the next update/delete can unwind. */
    public static final class Applied implements EngineApplied {
        @Getter
        private final Rule rule;
        @Getter
        private final MetricConvert metricConvert;
        @Getter
        private final Set<String> registeredMetricNames;
        /**
         * Per-file loader that owns every generated Metrics class for this apply. Retained
         * here as a strong reference so the classes stay live while the bundle is ACTIVE;
         * the dslManager retires it through {@code ClassLoaderGc} on unregister so GC is
         * observable.
         */
        @Getter
        private final RuleClassLoader ruleClassLoader;

        public Applied(final Rule rule, final MetricConvert metricConvert,
                       final Set<String> registeredMetricNames,
                       final RuleClassLoader ruleClassLoader) {
            this.rule = rule;
            this.metricConvert = metricConvert;
            this.registeredMetricNames = registeredMetricNames;
            this.ruleClassLoader = ruleClassLoader;
        }

        @Override
        public int suspendDispatch(final ModuleManager moduleManager) {
            if (registeredMetricNames == null || registeredMetricNames.isEmpty()) {
                return 0;
            }
            try {
                final MeterSystem ms = moduleManager.find(CoreModule.NAME).provider()
                                                    .getService(MeterSystem.class);
                return ms.suspendDispatch(registeredMetricNames);
            } catch (final Throwable t) {
                log.warn("runtime-rule MAL Applied: suspendDispatch lookup failed; "
                    + "next tick retries.", t);
                return 0;
            }
        }

        @Override
        public int resumeDispatch(final ModuleManager moduleManager) {
            if (registeredMetricNames == null || registeredMetricNames.isEmpty()) {
                return 0;
            }
            try {
                final MeterSystem ms = moduleManager.find(CoreModule.NAME).provider()
                                                    .getService(MeterSystem.class);
                return ms.resumeDispatch(registeredMetricNames);
            } catch (final Throwable t) {
                log.warn("runtime-rule MAL Applied: resumeDispatch lookup failed; "
                    + "next tick retries.", t);
                return 0;
            }
        }

        /** Cross-file ownership uses metric names: another active MAL bundle declaring the
         *  same {@code metricPrefix_metricName} is a config collision the operator must
         *  resolve before either side can apply. */
        @Override
        public Set<String> claimedKeys() {
            return registeredMetricNames == null
                ? Collections.emptySet()
                : registeredMetricNames;
        }

        @Override
        public Object classLoader() {
            return ruleClassLoader;
        }

        @Override
        public Set<String> alarmResetTargets() {
            return registeredMetricNames == null
                ? Collections.emptySet()
                : registeredMetricNames;
        }
    }

    /**
     * Uniform error type raised by {@link #apply}. Carries the {@code partiallyRegistered} set
     * so the caller can invoke {@link #remove} to roll back whatever made it through before
     * the failure.
     */
    public static final class ApplyException extends Exception {
        @Getter
        private final Set<String> partiallyRegistered;

        public ApplyException(final String message, final Throwable cause,
                              final Set<String> partiallyRegistered) {
            super(message, cause);
            this.partiallyRegistered = partiallyRegistered == null
                ? Collections.emptySet()
                : partiallyRegistered;
        }
    }

    /**
     * Raised by {@link #remove(Set, StorageManipulationOpt)} when one or more metric
     * teardowns failed. Unchecked so REST-sync callers can let it propagate without changing
     * method signatures across the call chain; the REST layer already catches
     * {@code Throwable} and surfaces it as 500 {@code teardown_deferred}. Cause is the first
     * underlying failure; the full map is retained on the exception for diagnostic logging.
     */
    public static final class RemoveException extends RuntimeException {
        @Getter
        private final Map<String, Throwable> failures;

        public RemoveException(final Map<String, Throwable> failures) {
            super(buildMessage(failures), firstCause(failures));
            this.failures = failures == null
                ? Collections.emptyMap()
                : Collections.unmodifiableMap(new LinkedHashMap<>(failures));
        }

        private static String buildMessage(final Map<String, Throwable> failures) {
            if (failures == null || failures.isEmpty()) {
                return "runtime-rule MAL remove failed (no failures recorded)";
            }
            final StringBuilder sb = new StringBuilder(
                "runtime-rule MAL remove failed for ").append(failures.size()).append(" metric(s): ");
            boolean first = true;
            for (final Map.Entry<String, Throwable> e : failures.entrySet()) {
                if (!first) {
                    sb.append(", ");
                }
                sb.append(e.getKey()).append(" (")
                  .append(e.getValue() == null ? "null" : e.getValue().getClass().getSimpleName())
                  .append(")");
                first = false;
            }
            return sb.toString();
        }

        private static Throwable firstCause(final Map<String, Throwable> failures) {
            if (failures == null || failures.isEmpty()) {
                return null;
            }
            return failures.values().iterator().next();
        }
    }
}
