/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.apache.skywalking.oap.server.core.classloader;

import java.net.URL;
import java.net.URLClassLoader;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import lombok.Getter;

/**
 * Per-file classloader that isolates all classes generated for one DSL rule file. Created
 * exclusively through {@link DSLClassLoaderManager#newBuilder}; callers never instantiate
 * directly so the manager owns the install / retire lifecycle uniformly across static and
 * runtime origins.
 *
 * <p>Hosts three artifact families produced by a MAL rule file's compile step — the
 * {@code MalExpression} subclass, closure companion classes, and the {@code Metrics} subclass
 * that {@code MeterSystem} generates for each declared metric name. For LAL, hosts the
 * {@code LalExpression} subclass + sub-method classes plus any inline {@code Metrics}
 * subclasses reached through the LAL→MAL bridge.
 *
 * <p>All three families living in one classloader gives a single drop-point on hot-remove:
 * when the bundle retires, the manager releases the last strong reference and the JVM can
 * collect every class the loader defined. The internal phantom-reference queue observes the
 * collection so an operator-visible WARN fires when a retired loader stays alive past the
 * configured threshold (the leak signal).
 *
 * <p>Parent is the OAP app classloader so parent-first lookup resolves shipped classes like
 * {@code SumFunction}, {@code HistogramFunction}, {@code MalExpression}, {@code LalExpression}
 * without shadowing. No URLs are added; we rely on the Javassist companion {@code ClassPool}
 * (parented to {@code ClassPool.getDefault()} with {@code LoaderClassPath(this)} appended)
 * to inject generated bytecode back into this loader via {@code defineClass}.
 */
public final class RuleClassLoader extends URLClassLoader implements BytecodeClassDefiner {
    private static final DateTimeFormatter NAME_TS = DateTimeFormatter.ofPattern("MMdd-HHmmss");

    /** Origin tag — {@link DSLClassLoaderManager.Kind#STATIC} for fall-over reload of bundled
     *  rules; {@link DSLClassLoaderManager.Kind#RUNTIME} for operator-pushed overrides. Visible
     *  in {@link #getName()} via the {@code static:} / {@code runtime-rule:} prefix. */
    @Getter
    private final DSLClassLoaderManager.Kind kind;
    @Getter
    private final Catalog catalog;
    /** Rule identity within the catalog. Renamed from the previous {@code name} field to avoid
     *  shadowing {@link URLClassLoader#getName()} — that getter must still surface the formatted
     *  loader name {@code "<kind>:<catalog>/<rule>@<ts>"} so log output stays unambiguous. */
    @Getter
    private final String rule;
    @Getter
    private final String contentHash;

    public RuleClassLoader(final DSLClassLoaderManager.Kind kind, final Catalog catalog,
                           final String rule, final String contentHash, final ClassLoader parent) {
        super(buildLoaderName(kind, catalog, rule), new URL[0], parent);
        this.kind = kind;
        this.catalog = catalog;
        this.rule = rule;
        this.contentHash = contentHash;
    }

    /**
     * Bytecode-injection entry point used by {@link
     * org.apache.skywalking.oap.server.core.analysis.meter.MeterSystem MeterSystem}'s
     * runtime-rule path and by Javassist's MAL / LAL generators after they call {@code
     * CtClass.toBytecode()}. Goes straight through {@code URLClassLoader.defineClass} —
     * no Javassist {@code toClass(loader, ProtectionDomain)} reflection, no JDK 17+
     * {@code --add-opens java.base/java.lang} requirement on the OAP container.
     *
     * <p>Implements {@link BytecodeClassDefiner} so callers in {@code server-core} can
     * type-check against the contract without taking a compile-time dep on the runtime-rule
     * receiver plugin.
     */
    @Override
    public Class<?> defineClass(final String className, final byte[] bytecode) {
        return defineClass(className, bytecode, 0, bytecode.length);
    }

    private static String buildLoaderName(final DSLClassLoaderManager.Kind kind,
                                          final Catalog catalog, final String rule) {
        final String prefix = kind == DSLClassLoaderManager.Kind.STATIC ? "static" : "runtime-rule";
        return prefix + ":" + catalog.getWireName() + "/" + rule
            + "@" + LocalDateTime.now().format(NAME_TS);
    }
}
