{
 "title": "SkyWalking OAP Cluster Monitor Dashboard",
 "description": "SkyWalking OAP Cluster Monitor Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances Number",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(uptime{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Instances Start Time",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Instances Run Time",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU * Cores number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{job=\"$job\"}[1m]) * 100 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"$job\",area=\"heap\"}",
     "legendFormat": "{{instance}}-used"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"$job\",area=\"heap\"}",
     "legendFormat": "{{instance}}-committed"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"$job\",area=\"heap\"}",
     "legendFormat": "{{instance}}-max"
    },
    {
     "expr": "jvm_memory_bytes_init{job=\"$job\",area=\"heap\"}",
     "legendFormat": "{{instance}}-init"
    }
   ]
  },
  {
   "title": "GC Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"$job\"}",
     "legendFormat": "{{instance}}-{{pool}}-used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"$job\"}",
     "legendFormat": "{{instance}}-{{pool}}-committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{job=\"$job\"}",
     "legendFormat": "{{instance}}-{{pool}}-max"
    },
    {
     "expr": "jvm_memory_pool_bytes_init{job=\"$job\"}",
     "legendFormat": "{{instance}}-{{pool}}-init"
    }
   ]
  },
  {
   "title": "Nonheap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"$job\",area=\"nonheap\"}",
     "legendFormat": "{{instance}}-used"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"$job\",area=\"nonheap\"}",
     "legendFormat": "{{instance}}-committed"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"$job\",area=\"nonheap\"}",
     "legendFormat": "{{instance}}-max"
    },
    {
     "expr": "jvm_memory_bytes_init{job=\"$job\",area=\"nonheap\"}",
     "legendFormat": "{{instance}}-init"
    }
   ]
  },
  {
   "title": "GC Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\"}",
     "legendFormat": "{{instance}}-Current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\"}",
     "legendFormat": "{{instance}}-Daemon"
    },
    {
     "expr": "jvm_threads_peak{job=\"$job\"}",
     "legendFormat": "{{instance}}-Peak"
    }
   ]
  },
  {
   "title": "JVM Thread State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"$job\"}",
     "legendFormat": "{{instance}}-{{state}}"
    }
   ]
  },
  {
   "title": "Class Loaded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "OAP Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Trace Segment Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(trace_in_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(trace_in_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Trace Segment Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(trace_in_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Trace Segment Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(trace_analysis_error_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Mesh Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mesh_analysis_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(mesh_analysis_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mesh Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_analysis_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mesh Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_analysis_error_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Meter Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(meter_in_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(meter_in_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Meter Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(meter_in_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Meter Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(meter_analysis_error_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Log Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_in_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(log_in_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Log Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(log_in_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Log Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(log_analysis_error_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Event Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(event_in_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(event_in_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Event Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(event_in_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Event Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(event_error_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Perf Data Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(browser_perf_data_in_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(browser_perf_data_in_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Perf Data Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(browser_perf_data_in_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Perf Data Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(browser_perf_data_analysis_error_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Error Log Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(browser_error_log_in_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(browser_error_log_in_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Error Log Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(browser_error_log_in_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Error Log Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(browser_error_log_analysis_error_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Metrics Fetcher Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metrics_fetcher_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(metrics_fetcher_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics Fetcher Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(metrics_fetcher_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics Fetcher Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metrics_fetcher_error_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Trace Segment Received Count / Hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(trace_in_latency_count{job=\"$job\",protocol=~\"kafka-fetcher|grpc\"}[1h]))",
     "legendFormat": "Current Week"
    },
    {
     "expr": "sum(increase(trace_in_latency_count{job=\"$job\",protocol=~\"kafka-fetcher|grpc\"}[1h] offset 1w))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Trace Segment Received Count / Day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(trace_in_latency_count{job=\"$job\",protocol=~\"kafka-fetcher|grpc\"}[1d]))",
     "legendFormat": "Current Week"
    },
    {
     "expr": "sum(increase(trace_in_latency_count{job=\"$job\",protocol=~\"kafka-fetcher|grpc\"}[1d] offset 1w))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Metrics Aggregation (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(metrics_aggregation{job=\"$job\"}[1m])) by (level)",
     "legendFormat": "Level{{level}}"
    }
   ]
  },
  {
   "title": "Remote Out Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(remote_out_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(remote_out_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}} -> {{dest}}"
    }
   ]
  },
  {
   "title": "Remote In Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(remote_in_latency_count{job=\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(remote_in_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics Aggregation Total Count",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 80 },
   "targets": [
    {
     "expr": "sum(metrics_aggregation{job=\"$job\"}) by (metricName)",
     "legendFormat": "{{metricName}}"
    }
   ]
  },
  {
   "title": "Persistence Prepare Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_prepare_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Persistence Prepare Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_prepare_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Persistence Execution Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_execute_latency_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Persistence Execution Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_execute_latency_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Persistence Bulk Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_error_count{job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}