{
 "title": "SkyWalking OAP Instance Monitor Dashboard",
 "description": "SkyWalking OAP Instance Monitor Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(process_cpu_seconds_total{job=\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\",instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Run Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Info",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "label_join(jvm_info{job=\"$job\",instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "CPU * Cores number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}[1m]) * 100 / 60",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "process_max_fds{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Thread Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "JVM Thread State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "JVM Thread Started Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_started_total{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Started Total"
    }
   ]
  },
  { "title": "Memory Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Heap/Nonheap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{area}}-used"
    },
    {
     "expr": "jvm_memory_bytes_committed{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{area}}-committed"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{area}}-max"
    },
    {
     "expr": "jvm_memory_bytes_init{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{area}}-init"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{pool}}-used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{pool}}-committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{pool}}-max"
    },
    {
     "expr": "jvm_memory_pool_bytes_init{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{pool}}-init"
    }
   ]
  },
  {
   "title": "Memory Pool Allocated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_memory_pool_allocated_bytes_total{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "GC Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "GC Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Classes Loaded Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "jvm_classes_loaded"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_classes_unloaded_total{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  { "title": "Buffer Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Buffer Pool Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{pool}}-used"
    },
    {
     "expr": "jvm_buffer_pool_capacity_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{pool}}-capacity"
    }
   ]
  },
  {
   "title": "Buffer Pool Buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_buffers{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "OAP Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Trace Segment Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(trace_in_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Trace Segment Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(trace_in_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Trace Segment Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(trace_analysis_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Mesh Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mesh_analysis_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Mesh Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_analysis_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Mesh Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mesh_analysis_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Meter Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(meter_in_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Meter Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(meter_in_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Meter Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(meter_analysis_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Log Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(log_in_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Log Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(log_in_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Log Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(log_analysis_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Event Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(event_in_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Event Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(event_in_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Event Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(event_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Perf Data Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(browser_perf_data_in_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Perf Data Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(browser_perf_data_in_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Perf Data Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(browser_perf_data_analysis_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Error Log Received Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(browser_error_log_in_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Error Log Analysis Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(browser_error_log_in_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Browser Error Log Analysis Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(browser_error_log_analysis_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Metrics Fetcher Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_fetcher_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Metrics Fetcher Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(metrics_fetcher_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Metrics Fetcher Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metrics_fetcher_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Trace Segment Received Count / Hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(trace_in_latency_count{job=\"$job\",instance=\"$instance\",protocol=~\"kafka-fetcher|grpc\"}[1h]))",
     "legendFormat": "Current Week"
    },
    {
     "expr": "sum(increase(trace_in_latency_count{job=\"$job\",instance=\"$instance\",protocol=~\"kafka-fetcher|grpc\"}[1h] offset 1w))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Trace Segment Received Count / Day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(trace_in_latency_count{job=\"$job\",instance=\"$instance\",protocol=~\"kafka-fetcher|grpc\"}[1d]))",
     "legendFormat": "Current Week"
    },
    {
     "expr": "sum(increase(trace_in_latency_count{job=\"$job\",instance=\"$instance\",protocol=~\"kafka-fetcher|grpc\"}[1d] offset 1w))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Metrics Aggregation (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(metrics_aggregation {instance=\"$instance\",job=\"$job\"} [1m])) by (level)",
     "legendFormat": "Level{{level}}"
    }
   ]
  },
  {
   "title": "Remote Out Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(remote_out_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}->{{dest}}"
    }
   ]
  },
  {
   "title": "Remote In Count / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(remote_in_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics Aggregation Total Count",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 100 },
   "targets": [
    {
     "expr": "sum(metrics_aggregation{instance=\"$instance\",job=\"$job\"}) by (metricName)",
     "legendFormat": "{{metricName}}"
    }
   ]
  },
  {
   "title": "Persistence Prepare Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_prepare_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "Prepare Count"
    }
   ]
  },
  {
   "title": "Persistence Prepare Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 106 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_prepare_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "Prepare Time"
    }
   ]
  },
  {
   "title": "Persistence Execution Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_execute_latency_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "Execution Count"
    }
   ]
  },
  {
   "title": "Persistence Execution Time (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_execute_latency_sum{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "Execution Time"
    }
   ]
  },
  {
   "title": "Persistence Bulk Error Count (Increment) / Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(persistence_timer_bulk_error_count{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "Bulk Error Count"
    }
   ]
  }
 ]
}