// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package com.a.eye.skywalking.trace.proto;

public interface KeyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:KeyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>optional string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
