// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package com.a.eye.skywalking.trace.proto;

/**
 * Protobuf type {@code LogDataMessage}
 */
public  final class LogDataMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LogDataMessage)
    LogDataMessageOrBuilder {
  // Use LogDataMessage.newBuilder() to construct.
  private LogDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogDataMessage() {
    time_ = 0L;
    fields_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LogDataMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              fields_ = new java.util.ArrayList<com.a.eye.skywalking.trace.proto.KeyValue>();
              mutable_bitField0_ |= 0x00000002;
            }
            fields_.add(
                input.readMessage(com.a.eye.skywalking.trace.proto.KeyValue.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        fields_ = java.util.Collections.unmodifiableList(fields_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.a.eye.skywalking.trace.proto.Trace.internal_static_LogDataMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.a.eye.skywalking.trace.proto.Trace.internal_static_LogDataMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.a.eye.skywalking.trace.proto.LogDataMessage.class, com.a.eye.skywalking.trace.proto.LogDataMessage.Builder.class);
  }

  private int bitField0_;
  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <code>optional int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int FIELDS_FIELD_NUMBER = 5;
  private java.util.List<com.a.eye.skywalking.trace.proto.KeyValue> fields_;
  /**
   * <code>repeated .KeyValue fields = 5;</code>
   */
  public java.util.List<com.a.eye.skywalking.trace.proto.KeyValue> getFieldsList() {
    return fields_;
  }
  /**
   * <code>repeated .KeyValue fields = 5;</code>
   */
  public java.util.List<? extends com.a.eye.skywalking.trace.proto.KeyValueOrBuilder> 
      getFieldsOrBuilderList() {
    return fields_;
  }
  /**
   * <code>repeated .KeyValue fields = 5;</code>
   */
  public int getFieldsCount() {
    return fields_.size();
  }
  /**
   * <code>repeated .KeyValue fields = 5;</code>
   */
  public com.a.eye.skywalking.trace.proto.KeyValue getFields(int index) {
    return fields_.get(index);
  }
  /**
   * <code>repeated .KeyValue fields = 5;</code>
   */
  public com.a.eye.skywalking.trace.proto.KeyValueOrBuilder getFieldsOrBuilder(
      int index) {
    return fields_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      output.writeMessage(5, fields_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, fields_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.a.eye.skywalking.trace.proto.LogDataMessage)) {
      return super.equals(obj);
    }
    com.a.eye.skywalking.trace.proto.LogDataMessage other = (com.a.eye.skywalking.trace.proto.LogDataMessage) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    result = result && getFieldsList()
        .equals(other.getFieldsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    if (getFieldsCount() > 0) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.LogDataMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.a.eye.skywalking.trace.proto.LogDataMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LogDataMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LogDataMessage)
      com.a.eye.skywalking.trace.proto.LogDataMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_LogDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_LogDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.a.eye.skywalking.trace.proto.LogDataMessage.class, com.a.eye.skywalking.trace.proto.LogDataMessage.Builder.class);
    }

    // Construct using com.a.eye.skywalking.trace.proto.LogDataMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFieldsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0L;

      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        fieldsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_LogDataMessage_descriptor;
    }

    public com.a.eye.skywalking.trace.proto.LogDataMessage getDefaultInstanceForType() {
      return com.a.eye.skywalking.trace.proto.LogDataMessage.getDefaultInstance();
    }

    public com.a.eye.skywalking.trace.proto.LogDataMessage build() {
      com.a.eye.skywalking.trace.proto.LogDataMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.a.eye.skywalking.trace.proto.LogDataMessage buildPartial() {
      com.a.eye.skywalking.trace.proto.LogDataMessage result = new com.a.eye.skywalking.trace.proto.LogDataMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.time_ = time_;
      if (fieldsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.fields_ = fields_;
      } else {
        result.fields_ = fieldsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.a.eye.skywalking.trace.proto.LogDataMessage) {
        return mergeFrom((com.a.eye.skywalking.trace.proto.LogDataMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.a.eye.skywalking.trace.proto.LogDataMessage other) {
      if (other == com.a.eye.skywalking.trace.proto.LogDataMessage.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (fieldsBuilder_ == null) {
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
      } else {
        if (!other.fields_.isEmpty()) {
          if (fieldsBuilder_.isEmpty()) {
            fieldsBuilder_.dispose();
            fieldsBuilder_ = null;
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000002);
            fieldsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFieldsFieldBuilder() : null;
          } else {
            fieldsBuilder_.addAllMessages(other.fields_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.a.eye.skywalking.trace.proto.LogDataMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.a.eye.skywalking.trace.proto.LogDataMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long time_ ;
    /**
     * <code>optional int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <code>optional int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.a.eye.skywalking.trace.proto.KeyValue> fields_ =
      java.util.Collections.emptyList();
    private void ensureFieldsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        fields_ = new java.util.ArrayList<com.a.eye.skywalking.trace.proto.KeyValue>(fields_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.a.eye.skywalking.trace.proto.KeyValue, com.a.eye.skywalking.trace.proto.KeyValue.Builder, com.a.eye.skywalking.trace.proto.KeyValueOrBuilder> fieldsBuilder_;

    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public java.util.List<com.a.eye.skywalking.trace.proto.KeyValue> getFieldsList() {
      if (fieldsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fields_);
      } else {
        return fieldsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public int getFieldsCount() {
      if (fieldsBuilder_ == null) {
        return fields_.size();
      } else {
        return fieldsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public com.a.eye.skywalking.trace.proto.KeyValue getFields(int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);
      } else {
        return fieldsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder setFields(
        int index, com.a.eye.skywalking.trace.proto.KeyValue value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder setFields(
        int index, com.a.eye.skywalking.trace.proto.KeyValue.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder addFields(com.a.eye.skywalking.trace.proto.KeyValue value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder addFields(
        int index, com.a.eye.skywalking.trace.proto.KeyValue value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(index, value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder addFields(
        com.a.eye.skywalking.trace.proto.KeyValue.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder addFields(
        int index, com.a.eye.skywalking.trace.proto.KeyValue.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder addAllFields(
        java.lang.Iterable<? extends com.a.eye.skywalking.trace.proto.KeyValue> values) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
      } else {
        fieldsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder clearFields() {
      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        fieldsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public Builder removeFields(int index) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.remove(index);
        onChanged();
      } else {
        fieldsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public com.a.eye.skywalking.trace.proto.KeyValue.Builder getFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public com.a.eye.skywalking.trace.proto.KeyValueOrBuilder getFieldsOrBuilder(
        int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);  } else {
        return fieldsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public java.util.List<? extends com.a.eye.skywalking.trace.proto.KeyValueOrBuilder> 
         getFieldsOrBuilderList() {
      if (fieldsBuilder_ != null) {
        return fieldsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fields_);
      }
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public com.a.eye.skywalking.trace.proto.KeyValue.Builder addFieldsBuilder() {
      return getFieldsFieldBuilder().addBuilder(
          com.a.eye.skywalking.trace.proto.KeyValue.getDefaultInstance());
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public com.a.eye.skywalking.trace.proto.KeyValue.Builder addFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().addBuilder(
          index, com.a.eye.skywalking.trace.proto.KeyValue.getDefaultInstance());
    }
    /**
     * <code>repeated .KeyValue fields = 5;</code>
     */
    public java.util.List<com.a.eye.skywalking.trace.proto.KeyValue.Builder> 
         getFieldsBuilderList() {
      return getFieldsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.a.eye.skywalking.trace.proto.KeyValue, com.a.eye.skywalking.trace.proto.KeyValue.Builder, com.a.eye.skywalking.trace.proto.KeyValueOrBuilder> 
        getFieldsFieldBuilder() {
      if (fieldsBuilder_ == null) {
        fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.a.eye.skywalking.trace.proto.KeyValue, com.a.eye.skywalking.trace.proto.KeyValue.Builder, com.a.eye.skywalking.trace.proto.KeyValueOrBuilder>(
                fields_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        fields_ = null;
      }
      return fieldsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:LogDataMessage)
  }

  // @@protoc_insertion_point(class_scope:LogDataMessage)
  private static final com.a.eye.skywalking.trace.proto.LogDataMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.a.eye.skywalking.trace.proto.LogDataMessage();
  }

  public static com.a.eye.skywalking.trace.proto.LogDataMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogDataMessage>
      PARSER = new com.google.protobuf.AbstractParser<LogDataMessage>() {
    public LogDataMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogDataMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LogDataMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LogDataMessage> getParserForType() {
    return PARSER;
  }

  public com.a.eye.skywalking.trace.proto.LogDataMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

