// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package com.a.eye.skywalking.trace.proto;

/**
 * Protobuf type {@code SegmentRefMessage}
 */
public  final class SegmentRefMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SegmentRefMessage)
    SegmentRefMessageOrBuilder {
  // Use SegmentRefMessage.newBuilder() to construct.
  private SegmentRefMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentRefMessage() {
    traceSegmentId_ = "";
    spanId_ = 0;
    applicationCode_ = "";
    peerHost_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SegmentRefMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            traceSegmentId_ = s;
            break;
          }
          case 16: {

            spanId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            applicationCode_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            peerHost_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentRefMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentRefMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.a.eye.skywalking.trace.proto.SegmentRefMessage.class, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder.class);
  }

  public static final int TRACESEGMENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object traceSegmentId_;
  /**
   * <code>optional string traceSegmentId = 1;</code>
   */
  public java.lang.String getTraceSegmentId() {
    java.lang.Object ref = traceSegmentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceSegmentId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string traceSegmentId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTraceSegmentIdBytes() {
    java.lang.Object ref = traceSegmentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceSegmentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPANID_FIELD_NUMBER = 2;
  private int spanId_;
  /**
   * <code>optional int32 spanId = 2;</code>
   */
  public int getSpanId() {
    return spanId_;
  }

  public static final int APPLICATIONCODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object applicationCode_;
  /**
   * <code>optional string applicationCode = 3;</code>
   */
  public java.lang.String getApplicationCode() {
    java.lang.Object ref = applicationCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      applicationCode_ = s;
      return s;
    }
  }
  /**
   * <code>optional string applicationCode = 3;</code>
   */
  public com.google.protobuf.ByteString
      getApplicationCodeBytes() {
    java.lang.Object ref = applicationCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      applicationCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEERHOST_FIELD_NUMBER = 4;
  private volatile java.lang.Object peerHost_;
  /**
   * <code>optional string peerHost = 4;</code>
   */
  public java.lang.String getPeerHost() {
    java.lang.Object ref = peerHost_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      peerHost_ = s;
      return s;
    }
  }
  /**
   * <code>optional string peerHost = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPeerHostBytes() {
    java.lang.Object ref = peerHost_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      peerHost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTraceSegmentIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceSegmentId_);
    }
    if (spanId_ != 0) {
      output.writeInt32(2, spanId_);
    }
    if (!getApplicationCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, applicationCode_);
    }
    if (!getPeerHostBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, peerHost_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTraceSegmentIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceSegmentId_);
    }
    if (spanId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, spanId_);
    }
    if (!getApplicationCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, applicationCode_);
    }
    if (!getPeerHostBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, peerHost_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.a.eye.skywalking.trace.proto.SegmentRefMessage)) {
      return super.equals(obj);
    }
    com.a.eye.skywalking.trace.proto.SegmentRefMessage other = (com.a.eye.skywalking.trace.proto.SegmentRefMessage) obj;

    boolean result = true;
    result = result && getTraceSegmentId()
        .equals(other.getTraceSegmentId());
    result = result && (getSpanId()
        == other.getSpanId());
    result = result && getApplicationCode()
        .equals(other.getApplicationCode());
    result = result && getPeerHost()
        .equals(other.getPeerHost());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TRACESEGMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceSegmentId().hashCode();
    hash = (37 * hash) + SPANID_FIELD_NUMBER;
    hash = (53 * hash) + getSpanId();
    hash = (37 * hash) + APPLICATIONCODE_FIELD_NUMBER;
    hash = (53 * hash) + getApplicationCode().hashCode();
    hash = (37 * hash) + PEERHOST_FIELD_NUMBER;
    hash = (53 * hash) + getPeerHost().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.a.eye.skywalking.trace.proto.SegmentRefMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SegmentRefMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SegmentRefMessage)
      com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentRefMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentRefMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.a.eye.skywalking.trace.proto.SegmentRefMessage.class, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder.class);
    }

    // Construct using com.a.eye.skywalking.trace.proto.SegmentRefMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      traceSegmentId_ = "";

      spanId_ = 0;

      applicationCode_ = "";

      peerHost_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentRefMessage_descriptor;
    }

    public com.a.eye.skywalking.trace.proto.SegmentRefMessage getDefaultInstanceForType() {
      return com.a.eye.skywalking.trace.proto.SegmentRefMessage.getDefaultInstance();
    }

    public com.a.eye.skywalking.trace.proto.SegmentRefMessage build() {
      com.a.eye.skywalking.trace.proto.SegmentRefMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.a.eye.skywalking.trace.proto.SegmentRefMessage buildPartial() {
      com.a.eye.skywalking.trace.proto.SegmentRefMessage result = new com.a.eye.skywalking.trace.proto.SegmentRefMessage(this);
      result.traceSegmentId_ = traceSegmentId_;
      result.spanId_ = spanId_;
      result.applicationCode_ = applicationCode_;
      result.peerHost_ = peerHost_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.a.eye.skywalking.trace.proto.SegmentRefMessage) {
        return mergeFrom((com.a.eye.skywalking.trace.proto.SegmentRefMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.a.eye.skywalking.trace.proto.SegmentRefMessage other) {
      if (other == com.a.eye.skywalking.trace.proto.SegmentRefMessage.getDefaultInstance()) return this;
      if (!other.getTraceSegmentId().isEmpty()) {
        traceSegmentId_ = other.traceSegmentId_;
        onChanged();
      }
      if (other.getSpanId() != 0) {
        setSpanId(other.getSpanId());
      }
      if (!other.getApplicationCode().isEmpty()) {
        applicationCode_ = other.applicationCode_;
        onChanged();
      }
      if (!other.getPeerHost().isEmpty()) {
        peerHost_ = other.peerHost_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.a.eye.skywalking.trace.proto.SegmentRefMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.a.eye.skywalking.trace.proto.SegmentRefMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object traceSegmentId_ = "";
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public java.lang.String getTraceSegmentId() {
      java.lang.Object ref = traceSegmentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceSegmentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceSegmentIdBytes() {
      java.lang.Object ref = traceSegmentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceSegmentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public Builder setTraceSegmentId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      traceSegmentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public Builder clearTraceSegmentId() {
      
      traceSegmentId_ = getDefaultInstance().getTraceSegmentId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public Builder setTraceSegmentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      traceSegmentId_ = value;
      onChanged();
      return this;
    }

    private int spanId_ ;
    /**
     * <code>optional int32 spanId = 2;</code>
     */
    public int getSpanId() {
      return spanId_;
    }
    /**
     * <code>optional int32 spanId = 2;</code>
     */
    public Builder setSpanId(int value) {
      
      spanId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 spanId = 2;</code>
     */
    public Builder clearSpanId() {
      
      spanId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object applicationCode_ = "";
    /**
     * <code>optional string applicationCode = 3;</code>
     */
    public java.lang.String getApplicationCode() {
      java.lang.Object ref = applicationCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicationCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string applicationCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getApplicationCodeBytes() {
      java.lang.Object ref = applicationCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string applicationCode = 3;</code>
     */
    public Builder setApplicationCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      applicationCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string applicationCode = 3;</code>
     */
    public Builder clearApplicationCode() {
      
      applicationCode_ = getDefaultInstance().getApplicationCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string applicationCode = 3;</code>
     */
    public Builder setApplicationCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      applicationCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object peerHost_ = "";
    /**
     * <code>optional string peerHost = 4;</code>
     */
    public java.lang.String getPeerHost() {
      java.lang.Object ref = peerHost_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerHost_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string peerHost = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPeerHostBytes() {
      java.lang.Object ref = peerHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string peerHost = 4;</code>
     */
    public Builder setPeerHost(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      peerHost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string peerHost = 4;</code>
     */
    public Builder clearPeerHost() {
      
      peerHost_ = getDefaultInstance().getPeerHost();
      onChanged();
      return this;
    }
    /**
     * <code>optional string peerHost = 4;</code>
     */
    public Builder setPeerHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      peerHost_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:SegmentRefMessage)
  }

  // @@protoc_insertion_point(class_scope:SegmentRefMessage)
  private static final com.a.eye.skywalking.trace.proto.SegmentRefMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.a.eye.skywalking.trace.proto.SegmentRefMessage();
  }

  public static com.a.eye.skywalking.trace.proto.SegmentRefMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SegmentRefMessage>
      PARSER = new com.google.protobuf.AbstractParser<SegmentRefMessage>() {
    public SegmentRefMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SegmentRefMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SegmentRefMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentRefMessage> getParserForType() {
    return PARSER;
  }

  public com.a.eye.skywalking.trace.proto.SegmentRefMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

