// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package com.a.eye.skywalking.trace.proto;

public interface SegmentMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SegmentMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string traceSegmentId = 1;</code>
   */
  java.lang.String getTraceSegmentId();
  /**
   * <code>optional string traceSegmentId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTraceSegmentIdBytes();

  /**
   * <code>optional int64 startTime = 2;</code>
   */
  long getStartTime();

  /**
   * <code>optional int64 endTime = 3;</code>
   */
  long getEndTime();

  /**
   * <code>optional string applicationCode = 4;</code>
   */
  java.lang.String getApplicationCode();
  /**
   * <code>optional string applicationCode = 4;</code>
   */
  com.google.protobuf.ByteString
      getApplicationCodeBytes();

  /**
   * <code>optional .SegmentRefMessage primaryRef = 5;</code>
   */
  boolean hasPrimaryRef();
  /**
   * <code>optional .SegmentRefMessage primaryRef = 5;</code>
   */
  com.a.eye.skywalking.trace.proto.SegmentRefMessage getPrimaryRef();
  /**
   * <code>optional .SegmentRefMessage primaryRef = 5;</code>
   */
  com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder getPrimaryRefOrBuilder();

  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  java.util.List<com.a.eye.skywalking.trace.proto.SegmentRefMessage> 
      getRefsList();
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  com.a.eye.skywalking.trace.proto.SegmentRefMessage getRefs(int index);
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  int getRefsCount();
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  java.util.List<? extends com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder> 
      getRefsOrBuilderList();
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder getRefsOrBuilder(
      int index);

  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  java.util.List<com.a.eye.skywalking.trace.proto.SpanMessage> 
      getSpansList();
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  com.a.eye.skywalking.trace.proto.SpanMessage getSpans(int index);
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  int getSpansCount();
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  java.util.List<? extends com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder> 
      getSpansOrBuilderList();
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder getSpansOrBuilder(
      int index);
}
