// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package com.a.eye.skywalking.trace.proto;

/**
 * Protobuf type {@code SegmentMessage}
 */
public  final class SegmentMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SegmentMessage)
    SegmentMessageOrBuilder {
  // Use SegmentMessage.newBuilder() to construct.
  private SegmentMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentMessage() {
    traceSegmentId_ = "";
    startTime_ = 0L;
    endTime_ = 0L;
    applicationCode_ = "";
    refs_ = java.util.Collections.emptyList();
    spans_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SegmentMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            traceSegmentId_ = s;
            break;
          }
          case 16: {

            startTime_ = input.readInt64();
            break;
          }
          case 24: {

            endTime_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            applicationCode_ = s;
            break;
          }
          case 42: {
            com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder subBuilder = null;
            if (primaryRef_ != null) {
              subBuilder = primaryRef_.toBuilder();
            }
            primaryRef_ = input.readMessage(com.a.eye.skywalking.trace.proto.SegmentRefMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(primaryRef_);
              primaryRef_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              refs_ = new java.util.ArrayList<com.a.eye.skywalking.trace.proto.SegmentRefMessage>();
              mutable_bitField0_ |= 0x00000020;
            }
            refs_.add(
                input.readMessage(com.a.eye.skywalking.trace.proto.SegmentRefMessage.parser(), extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              spans_ = new java.util.ArrayList<com.a.eye.skywalking.trace.proto.SpanMessage>();
              mutable_bitField0_ |= 0x00000040;
            }
            spans_.add(
                input.readMessage(com.a.eye.skywalking.trace.proto.SpanMessage.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        refs_ = java.util.Collections.unmodifiableList(refs_);
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        spans_ = java.util.Collections.unmodifiableList(spans_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.a.eye.skywalking.trace.proto.SegmentMessage.class, com.a.eye.skywalking.trace.proto.SegmentMessage.Builder.class);
  }

  private int bitField0_;
  public static final int TRACESEGMENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object traceSegmentId_;
  /**
   * <code>optional string traceSegmentId = 1;</code>
   */
  public java.lang.String getTraceSegmentId() {
    java.lang.Object ref = traceSegmentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceSegmentId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string traceSegmentId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTraceSegmentIdBytes() {
    java.lang.Object ref = traceSegmentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceSegmentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  private long startTime_;
  /**
   * <code>optional int64 startTime = 2;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 3;
  private long endTime_;
  /**
   * <code>optional int64 endTime = 3;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int APPLICATIONCODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object applicationCode_;
  /**
   * <code>optional string applicationCode = 4;</code>
   */
  public java.lang.String getApplicationCode() {
    java.lang.Object ref = applicationCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      applicationCode_ = s;
      return s;
    }
  }
  /**
   * <code>optional string applicationCode = 4;</code>
   */
  public com.google.protobuf.ByteString
      getApplicationCodeBytes() {
    java.lang.Object ref = applicationCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      applicationCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIMARYREF_FIELD_NUMBER = 5;
  private com.a.eye.skywalking.trace.proto.SegmentRefMessage primaryRef_;
  /**
   * <code>optional .SegmentRefMessage primaryRef = 5;</code>
   */
  public boolean hasPrimaryRef() {
    return primaryRef_ != null;
  }
  /**
   * <code>optional .SegmentRefMessage primaryRef = 5;</code>
   */
  public com.a.eye.skywalking.trace.proto.SegmentRefMessage getPrimaryRef() {
    return primaryRef_ == null ? com.a.eye.skywalking.trace.proto.SegmentRefMessage.getDefaultInstance() : primaryRef_;
  }
  /**
   * <code>optional .SegmentRefMessage primaryRef = 5;</code>
   */
  public com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder getPrimaryRefOrBuilder() {
    return getPrimaryRef();
  }

  public static final int REFS_FIELD_NUMBER = 6;
  private java.util.List<com.a.eye.skywalking.trace.proto.SegmentRefMessage> refs_;
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  public java.util.List<com.a.eye.skywalking.trace.proto.SegmentRefMessage> getRefsList() {
    return refs_;
  }
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  public java.util.List<? extends com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder> 
      getRefsOrBuilderList() {
    return refs_;
  }
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  public int getRefsCount() {
    return refs_.size();
  }
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  public com.a.eye.skywalking.trace.proto.SegmentRefMessage getRefs(int index) {
    return refs_.get(index);
  }
  /**
   * <code>repeated .SegmentRefMessage refs = 6;</code>
   */
  public com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder getRefsOrBuilder(
      int index) {
    return refs_.get(index);
  }

  public static final int SPANS_FIELD_NUMBER = 7;
  private java.util.List<com.a.eye.skywalking.trace.proto.SpanMessage> spans_;
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  public java.util.List<com.a.eye.skywalking.trace.proto.SpanMessage> getSpansList() {
    return spans_;
  }
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  public java.util.List<? extends com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder> 
      getSpansOrBuilderList() {
    return spans_;
  }
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  public int getSpansCount() {
    return spans_.size();
  }
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  public com.a.eye.skywalking.trace.proto.SpanMessage getSpans(int index) {
    return spans_.get(index);
  }
  /**
   * <code>repeated .SpanMessage spans = 7;</code>
   */
  public com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder getSpansOrBuilder(
      int index) {
    return spans_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTraceSegmentIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceSegmentId_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(2, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(3, endTime_);
    }
    if (!getApplicationCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, applicationCode_);
    }
    if (primaryRef_ != null) {
      output.writeMessage(5, getPrimaryRef());
    }
    for (int i = 0; i < refs_.size(); i++) {
      output.writeMessage(6, refs_.get(i));
    }
    for (int i = 0; i < spans_.size(); i++) {
      output.writeMessage(7, spans_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTraceSegmentIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceSegmentId_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, endTime_);
    }
    if (!getApplicationCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, applicationCode_);
    }
    if (primaryRef_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPrimaryRef());
    }
    for (int i = 0; i < refs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, refs_.get(i));
    }
    for (int i = 0; i < spans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, spans_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.a.eye.skywalking.trace.proto.SegmentMessage)) {
      return super.equals(obj);
    }
    com.a.eye.skywalking.trace.proto.SegmentMessage other = (com.a.eye.skywalking.trace.proto.SegmentMessage) obj;

    boolean result = true;
    result = result && getTraceSegmentId()
        .equals(other.getTraceSegmentId());
    result = result && (getStartTime()
        == other.getStartTime());
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && getApplicationCode()
        .equals(other.getApplicationCode());
    result = result && (hasPrimaryRef() == other.hasPrimaryRef());
    if (hasPrimaryRef()) {
      result = result && getPrimaryRef()
          .equals(other.getPrimaryRef());
    }
    result = result && getRefsList()
        .equals(other.getRefsList());
    result = result && getSpansList()
        .equals(other.getSpansList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TRACESEGMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceSegmentId().hashCode();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + APPLICATIONCODE_FIELD_NUMBER;
    hash = (53 * hash) + getApplicationCode().hashCode();
    if (hasPrimaryRef()) {
      hash = (37 * hash) + PRIMARYREF_FIELD_NUMBER;
      hash = (53 * hash) + getPrimaryRef().hashCode();
    }
    if (getRefsCount() > 0) {
      hash = (37 * hash) + REFS_FIELD_NUMBER;
      hash = (53 * hash) + getRefsList().hashCode();
    }
    if (getSpansCount() > 0) {
      hash = (37 * hash) + SPANS_FIELD_NUMBER;
      hash = (53 * hash) + getSpansList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.a.eye.skywalking.trace.proto.SegmentMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.a.eye.skywalking.trace.proto.SegmentMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SegmentMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SegmentMessage)
      com.a.eye.skywalking.trace.proto.SegmentMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.a.eye.skywalking.trace.proto.SegmentMessage.class, com.a.eye.skywalking.trace.proto.SegmentMessage.Builder.class);
    }

    // Construct using com.a.eye.skywalking.trace.proto.SegmentMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRefsFieldBuilder();
        getSpansFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      traceSegmentId_ = "";

      startTime_ = 0L;

      endTime_ = 0L;

      applicationCode_ = "";

      if (primaryRefBuilder_ == null) {
        primaryRef_ = null;
      } else {
        primaryRef_ = null;
        primaryRefBuilder_ = null;
      }
      if (refsBuilder_ == null) {
        refs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        refsBuilder_.clear();
      }
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        spansBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.a.eye.skywalking.trace.proto.Trace.internal_static_SegmentMessage_descriptor;
    }

    public com.a.eye.skywalking.trace.proto.SegmentMessage getDefaultInstanceForType() {
      return com.a.eye.skywalking.trace.proto.SegmentMessage.getDefaultInstance();
    }

    public com.a.eye.skywalking.trace.proto.SegmentMessage build() {
      com.a.eye.skywalking.trace.proto.SegmentMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.a.eye.skywalking.trace.proto.SegmentMessage buildPartial() {
      com.a.eye.skywalking.trace.proto.SegmentMessage result = new com.a.eye.skywalking.trace.proto.SegmentMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.traceSegmentId_ = traceSegmentId_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.applicationCode_ = applicationCode_;
      if (primaryRefBuilder_ == null) {
        result.primaryRef_ = primaryRef_;
      } else {
        result.primaryRef_ = primaryRefBuilder_.build();
      }
      if (refsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          refs_ = java.util.Collections.unmodifiableList(refs_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.refs_ = refs_;
      } else {
        result.refs_ = refsBuilder_.build();
      }
      if (spansBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          spans_ = java.util.Collections.unmodifiableList(spans_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.spans_ = spans_;
      } else {
        result.spans_ = spansBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.a.eye.skywalking.trace.proto.SegmentMessage) {
        return mergeFrom((com.a.eye.skywalking.trace.proto.SegmentMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.a.eye.skywalking.trace.proto.SegmentMessage other) {
      if (other == com.a.eye.skywalking.trace.proto.SegmentMessage.getDefaultInstance()) return this;
      if (!other.getTraceSegmentId().isEmpty()) {
        traceSegmentId_ = other.traceSegmentId_;
        onChanged();
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (!other.getApplicationCode().isEmpty()) {
        applicationCode_ = other.applicationCode_;
        onChanged();
      }
      if (other.hasPrimaryRef()) {
        mergePrimaryRef(other.getPrimaryRef());
      }
      if (refsBuilder_ == null) {
        if (!other.refs_.isEmpty()) {
          if (refs_.isEmpty()) {
            refs_ = other.refs_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureRefsIsMutable();
            refs_.addAll(other.refs_);
          }
          onChanged();
        }
      } else {
        if (!other.refs_.isEmpty()) {
          if (refsBuilder_.isEmpty()) {
            refsBuilder_.dispose();
            refsBuilder_ = null;
            refs_ = other.refs_;
            bitField0_ = (bitField0_ & ~0x00000020);
            refsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRefsFieldBuilder() : null;
          } else {
            refsBuilder_.addAllMessages(other.refs_);
          }
        }
      }
      if (spansBuilder_ == null) {
        if (!other.spans_.isEmpty()) {
          if (spans_.isEmpty()) {
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureSpansIsMutable();
            spans_.addAll(other.spans_);
          }
          onChanged();
        }
      } else {
        if (!other.spans_.isEmpty()) {
          if (spansBuilder_.isEmpty()) {
            spansBuilder_.dispose();
            spansBuilder_ = null;
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000040);
            spansBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpansFieldBuilder() : null;
          } else {
            spansBuilder_.addAllMessages(other.spans_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.a.eye.skywalking.trace.proto.SegmentMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.a.eye.skywalking.trace.proto.SegmentMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object traceSegmentId_ = "";
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public java.lang.String getTraceSegmentId() {
      java.lang.Object ref = traceSegmentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceSegmentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceSegmentIdBytes() {
      java.lang.Object ref = traceSegmentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceSegmentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public Builder setTraceSegmentId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      traceSegmentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public Builder clearTraceSegmentId() {
      
      traceSegmentId_ = getDefaultInstance().getTraceSegmentId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceSegmentId = 1;</code>
     */
    public Builder setTraceSegmentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      traceSegmentId_ = value;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>optional int64 startTime = 2;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>optional int64 startTime = 2;</code>
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 startTime = 2;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>optional int64 endTime = 3;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>optional int64 endTime = 3;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 endTime = 3;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object applicationCode_ = "";
    /**
     * <code>optional string applicationCode = 4;</code>
     */
    public java.lang.String getApplicationCode() {
      java.lang.Object ref = applicationCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicationCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string applicationCode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getApplicationCodeBytes() {
      java.lang.Object ref = applicationCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string applicationCode = 4;</code>
     */
    public Builder setApplicationCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      applicationCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string applicationCode = 4;</code>
     */
    public Builder clearApplicationCode() {
      
      applicationCode_ = getDefaultInstance().getApplicationCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string applicationCode = 4;</code>
     */
    public Builder setApplicationCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      applicationCode_ = value;
      onChanged();
      return this;
    }

    private com.a.eye.skywalking.trace.proto.SegmentRefMessage primaryRef_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.a.eye.skywalking.trace.proto.SegmentRefMessage, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder, com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder> primaryRefBuilder_;
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    public boolean hasPrimaryRef() {
      return primaryRefBuilder_ != null || primaryRef_ != null;
    }
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    public com.a.eye.skywalking.trace.proto.SegmentRefMessage getPrimaryRef() {
      if (primaryRefBuilder_ == null) {
        return primaryRef_ == null ? com.a.eye.skywalking.trace.proto.SegmentRefMessage.getDefaultInstance() : primaryRef_;
      } else {
        return primaryRefBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    public Builder setPrimaryRef(com.a.eye.skywalking.trace.proto.SegmentRefMessage value) {
      if (primaryRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        primaryRef_ = value;
        onChanged();
      } else {
        primaryRefBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    public Builder setPrimaryRef(
        com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder builderForValue) {
      if (primaryRefBuilder_ == null) {
        primaryRef_ = builderForValue.build();
        onChanged();
      } else {
        primaryRefBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    public Builder mergePrimaryRef(com.a.eye.skywalking.trace.proto.SegmentRefMessage value) {
      if (primaryRefBuilder_ == null) {
        if (primaryRef_ != null) {
          primaryRef_ =
            com.a.eye.skywalking.trace.proto.SegmentRefMessage.newBuilder(primaryRef_).mergeFrom(value).buildPartial();
        } else {
          primaryRef_ = value;
        }
        onChanged();
      } else {
        primaryRefBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    public Builder clearPrimaryRef() {
      if (primaryRefBuilder_ == null) {
        primaryRef_ = null;
        onChanged();
      } else {
        primaryRef_ = null;
        primaryRefBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    public com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder getPrimaryRefBuilder() {
      
      onChanged();
      return getPrimaryRefFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    public com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder getPrimaryRefOrBuilder() {
      if (primaryRefBuilder_ != null) {
        return primaryRefBuilder_.getMessageOrBuilder();
      } else {
        return primaryRef_ == null ?
            com.a.eye.skywalking.trace.proto.SegmentRefMessage.getDefaultInstance() : primaryRef_;
      }
    }
    /**
     * <code>optional .SegmentRefMessage primaryRef = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.a.eye.skywalking.trace.proto.SegmentRefMessage, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder, com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder> 
        getPrimaryRefFieldBuilder() {
      if (primaryRefBuilder_ == null) {
        primaryRefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.a.eye.skywalking.trace.proto.SegmentRefMessage, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder, com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder>(
                getPrimaryRef(),
                getParentForChildren(),
                isClean());
        primaryRef_ = null;
      }
      return primaryRefBuilder_;
    }

    private java.util.List<com.a.eye.skywalking.trace.proto.SegmentRefMessage> refs_ =
      java.util.Collections.emptyList();
    private void ensureRefsIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        refs_ = new java.util.ArrayList<com.a.eye.skywalking.trace.proto.SegmentRefMessage>(refs_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.a.eye.skywalking.trace.proto.SegmentRefMessage, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder, com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder> refsBuilder_;

    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public java.util.List<com.a.eye.skywalking.trace.proto.SegmentRefMessage> getRefsList() {
      if (refsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(refs_);
      } else {
        return refsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public int getRefsCount() {
      if (refsBuilder_ == null) {
        return refs_.size();
      } else {
        return refsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public com.a.eye.skywalking.trace.proto.SegmentRefMessage getRefs(int index) {
      if (refsBuilder_ == null) {
        return refs_.get(index);
      } else {
        return refsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder setRefs(
        int index, com.a.eye.skywalking.trace.proto.SegmentRefMessage value) {
      if (refsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRefsIsMutable();
        refs_.set(index, value);
        onChanged();
      } else {
        refsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder setRefs(
        int index, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder builderForValue) {
      if (refsBuilder_ == null) {
        ensureRefsIsMutable();
        refs_.set(index, builderForValue.build());
        onChanged();
      } else {
        refsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder addRefs(com.a.eye.skywalking.trace.proto.SegmentRefMessage value) {
      if (refsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRefsIsMutable();
        refs_.add(value);
        onChanged();
      } else {
        refsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder addRefs(
        int index, com.a.eye.skywalking.trace.proto.SegmentRefMessage value) {
      if (refsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRefsIsMutable();
        refs_.add(index, value);
        onChanged();
      } else {
        refsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder addRefs(
        com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder builderForValue) {
      if (refsBuilder_ == null) {
        ensureRefsIsMutable();
        refs_.add(builderForValue.build());
        onChanged();
      } else {
        refsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder addRefs(
        int index, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder builderForValue) {
      if (refsBuilder_ == null) {
        ensureRefsIsMutable();
        refs_.add(index, builderForValue.build());
        onChanged();
      } else {
        refsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder addAllRefs(
        java.lang.Iterable<? extends com.a.eye.skywalking.trace.proto.SegmentRefMessage> values) {
      if (refsBuilder_ == null) {
        ensureRefsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, refs_);
        onChanged();
      } else {
        refsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder clearRefs() {
      if (refsBuilder_ == null) {
        refs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        refsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public Builder removeRefs(int index) {
      if (refsBuilder_ == null) {
        ensureRefsIsMutable();
        refs_.remove(index);
        onChanged();
      } else {
        refsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder getRefsBuilder(
        int index) {
      return getRefsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder getRefsOrBuilder(
        int index) {
      if (refsBuilder_ == null) {
        return refs_.get(index);  } else {
        return refsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public java.util.List<? extends com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder> 
         getRefsOrBuilderList() {
      if (refsBuilder_ != null) {
        return refsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(refs_);
      }
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder addRefsBuilder() {
      return getRefsFieldBuilder().addBuilder(
          com.a.eye.skywalking.trace.proto.SegmentRefMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder addRefsBuilder(
        int index) {
      return getRefsFieldBuilder().addBuilder(
          index, com.a.eye.skywalking.trace.proto.SegmentRefMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .SegmentRefMessage refs = 6;</code>
     */
    public java.util.List<com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder> 
         getRefsBuilderList() {
      return getRefsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.a.eye.skywalking.trace.proto.SegmentRefMessage, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder, com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder> 
        getRefsFieldBuilder() {
      if (refsBuilder_ == null) {
        refsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.a.eye.skywalking.trace.proto.SegmentRefMessage, com.a.eye.skywalking.trace.proto.SegmentRefMessage.Builder, com.a.eye.skywalking.trace.proto.SegmentRefMessageOrBuilder>(
                refs_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        refs_ = null;
      }
      return refsBuilder_;
    }

    private java.util.List<com.a.eye.skywalking.trace.proto.SpanMessage> spans_ =
      java.util.Collections.emptyList();
    private void ensureSpansIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        spans_ = new java.util.ArrayList<com.a.eye.skywalking.trace.proto.SpanMessage>(spans_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.a.eye.skywalking.trace.proto.SpanMessage, com.a.eye.skywalking.trace.proto.SpanMessage.Builder, com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder> spansBuilder_;

    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public java.util.List<com.a.eye.skywalking.trace.proto.SpanMessage> getSpansList() {
      if (spansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(spans_);
      } else {
        return spansBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public int getSpansCount() {
      if (spansBuilder_ == null) {
        return spans_.size();
      } else {
        return spansBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public com.a.eye.skywalking.trace.proto.SpanMessage getSpans(int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);
      } else {
        return spansBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder setSpans(
        int index, com.a.eye.skywalking.trace.proto.SpanMessage value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.set(index, value);
        onChanged();
      } else {
        spansBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder setSpans(
        int index, com.a.eye.skywalking.trace.proto.SpanMessage.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.set(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder addSpans(com.a.eye.skywalking.trace.proto.SpanMessage value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(value);
        onChanged();
      } else {
        spansBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder addSpans(
        int index, com.a.eye.skywalking.trace.proto.SpanMessage value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(index, value);
        onChanged();
      } else {
        spansBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder addSpans(
        com.a.eye.skywalking.trace.proto.SpanMessage.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder addSpans(
        int index, com.a.eye.skywalking.trace.proto.SpanMessage.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder addAllSpans(
        java.lang.Iterable<? extends com.a.eye.skywalking.trace.proto.SpanMessage> values) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, spans_);
        onChanged();
      } else {
        spansBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder clearSpans() {
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        spansBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public Builder removeSpans(int index) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.remove(index);
        onChanged();
      } else {
        spansBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public com.a.eye.skywalking.trace.proto.SpanMessage.Builder getSpansBuilder(
        int index) {
      return getSpansFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder getSpansOrBuilder(
        int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);  } else {
        return spansBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public java.util.List<? extends com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder> 
         getSpansOrBuilderList() {
      if (spansBuilder_ != null) {
        return spansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(spans_);
      }
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public com.a.eye.skywalking.trace.proto.SpanMessage.Builder addSpansBuilder() {
      return getSpansFieldBuilder().addBuilder(
          com.a.eye.skywalking.trace.proto.SpanMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public com.a.eye.skywalking.trace.proto.SpanMessage.Builder addSpansBuilder(
        int index) {
      return getSpansFieldBuilder().addBuilder(
          index, com.a.eye.skywalking.trace.proto.SpanMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .SpanMessage spans = 7;</code>
     */
    public java.util.List<com.a.eye.skywalking.trace.proto.SpanMessage.Builder> 
         getSpansBuilderList() {
      return getSpansFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.a.eye.skywalking.trace.proto.SpanMessage, com.a.eye.skywalking.trace.proto.SpanMessage.Builder, com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder> 
        getSpansFieldBuilder() {
      if (spansBuilder_ == null) {
        spansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.a.eye.skywalking.trace.proto.SpanMessage, com.a.eye.skywalking.trace.proto.SpanMessage.Builder, com.a.eye.skywalking.trace.proto.SpanMessageOrBuilder>(
                spans_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        spans_ = null;
      }
      return spansBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:SegmentMessage)
  }

  // @@protoc_insertion_point(class_scope:SegmentMessage)
  private static final com.a.eye.skywalking.trace.proto.SegmentMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.a.eye.skywalking.trace.proto.SegmentMessage();
  }

  public static com.a.eye.skywalking.trace.proto.SegmentMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SegmentMessage>
      PARSER = new com.google.protobuf.AbstractParser<SegmentMessage>() {
    public SegmentMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SegmentMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SegmentMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentMessage> getParserForType() {
    return PARSER;
  }

  public com.a.eye.skywalking.trace.proto.SegmentMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

