// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package com.a.eye.skywalking.trace.proto;

public interface SpanMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpanMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 spanId = 1;</code>
   */
  int getSpanId();

  /**
   * <code>optional int64 startTime = 2;</code>
   */
  long getStartTime();

  /**
   * <code>optional int64 endTime = 3;</code>
   */
  long getEndTime();

  /**
   * <code>optional string operationName = 4;</code>
   */
  java.lang.String getOperationName();
  /**
   * <code>optional string operationName = 4;</code>
   */
  com.google.protobuf.ByteString
      getOperationNameBytes();

  /**
   * <code>repeated .KeyValue tags = 5;</code>
   */
  java.util.List<com.a.eye.skywalking.trace.proto.KeyValue> 
      getTagsList();
  /**
   * <code>repeated .KeyValue tags = 5;</code>
   */
  com.a.eye.skywalking.trace.proto.KeyValue getTags(int index);
  /**
   * <code>repeated .KeyValue tags = 5;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .KeyValue tags = 5;</code>
   */
  java.util.List<? extends com.a.eye.skywalking.trace.proto.KeyValueOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <code>repeated .KeyValue tags = 5;</code>
   */
  com.a.eye.skywalking.trace.proto.KeyValueOrBuilder getTagsOrBuilder(
      int index);

  /**
   * <code>repeated .LogDataMessage logs = 6;</code>
   */
  java.util.List<com.a.eye.skywalking.trace.proto.LogDataMessage> 
      getLogsList();
  /**
   * <code>repeated .LogDataMessage logs = 6;</code>
   */
  com.a.eye.skywalking.trace.proto.LogDataMessage getLogs(int index);
  /**
   * <code>repeated .LogDataMessage logs = 6;</code>
   */
  int getLogsCount();
  /**
   * <code>repeated .LogDataMessage logs = 6;</code>
   */
  java.util.List<? extends com.a.eye.skywalking.trace.proto.LogDataMessageOrBuilder> 
      getLogsOrBuilderList();
  /**
   * <code>repeated .LogDataMessage logs = 6;</code>
   */
  com.a.eye.skywalking.trace.proto.LogDataMessageOrBuilder getLogsOrBuilder(
      int index);
}
