{
 "title": "SkyWalking mesh-mode dashboard",
 "description": "Metric for skywalking backend",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "instances number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(uptime)" }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total[1m])) * 100 / 60"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_gc_collection_seconds_sum) / sum(jvm_gc_collection_seconds_count)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used) / 1000 / 1000"
    }
   ]
  },
  {
   "title": "Mesh telemetry received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mesh_grpc_in_latency_count[1m])",
     "legendFormat": "{{sw_backend_instance}}"
    }
   ]
  },
  {
   "title": "mesh telemetry latency",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "rate(mesh_grpc_in_latency_bucket[10m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "mesh telemetry buffer file in",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(mesh_buffer_file_in[1m])", "legendFormat": "{{sw_backend_instance}}" }
   ]
  },
  {
   "title": "mesh telemetry retry buffer file",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mesh_buffer_file_retry[1m])",
     "legendFormat": "{{sw_backend_instance}}"
    }
   ]
  },
  {
   "title": "mesh telemetry out of buffer file",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mesh_buffer_file_out[1m]) ",
     "legendFormat": "{{sw_backend_instance}}"
    }
   ]
  },
  {
   "title": "Persistence execution count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(persistence_timer_bulk_prepare_latency_count[1m])",
     "legendFormat": "{{sw_backend_instance}}-prepare"
    },
    {
     "expr": "rate(persistence_timer_bulk_error_count[1m])",
     "legendFormat": "{{sw_backend_instance}}-error"
    },
    {
     "expr": "rate(persistence_timer_bulk_execute_latency_count[1m])",
     "legendFormat": "{{sw_backend_instance}}-execute"
    }
   ]
  },
  {
   "title": "persistent latency",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "rate(persistence_timer_bulk_execute_latency_bucket[10m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Persistence time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "persistence_timer_bulk_prepare_latency_sum / persistence_timer_bulk_prepare_latency_count",
     "legendFormat": "{{sw_backend_instance}}-prepare"
    },
    {
     "expr": "persistence_timer_bulk_execute_latency_sum / persistence_timer_bulk_execute_latency_count",
     "legendFormat": "{{sw_backend_instance}}-execute"
    }
   ]
  },
  {
   "title": "Aggregation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indicator_aggregation {dimensionality=\"min\"} [1m])) by (level)"
    }
   ]
  }
 ]
}