/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.apache.skywalking.oap.meter.analyzer.v2.dsl;

import java.util.Map;
import org.apache.skywalking.oap.server.core.dsldebug.GateHolder;

/**
 * Each compiled MAL expression implements this interface.
 */
public interface MalExpression {
    SampleFamily run(Map<String, SampleFamily> samples);

    /**
     * Returns compile-time metadata extracted from the expression AST:
     * sample names, scope type, aggregation labels, downsampling, etc.
     */
    ExpressionMetadata metadata();

    /**
     * Returns the per-rule capture binding the generated bytecode reads on
     * every probe call site. Codegen emits the {@code public final GateHolder
     * DEBUG} field + the override only when
     * {@link org.apache.skywalking.oap.server.core.dsldebug.DSLDebugCodegenSwitch#isInjectionEnabled()
     * dsl-debugging is enabled at boot}. When injection is off, this default
     * returns {@code null} and the session-install path treats that as
     * "no live holder for this rule" (i.e. the session is not capturable on
     * this node).
     */
    default GateHolder debugHolder() {
        return null;
    }
}
