# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    openai==2.31.0 \
    opentelemetry-api==1.41.0 \
    opentelemetry-sdk==1.41.0 \
    opentelemetry-instrumentation==0.62b0 \
    opentelemetry-instrumentation-openai==0.58.0 \
    opentelemetry-exporter-otlp-proto-grpc==1.41.0 \
    opentelemetry-exporter-zipkin-json==1.41.0 \
    opentelemetry-distro==0.62b0

COPY python/openai-call.py /openai-call.py

