# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir openai
RUN pip install --no-cache-dir opentelemetry-api
RUN pip install --no-cache-dir opentelemetry-sdk
RUN pip install --no-cache-dir opentelemetry-instrumentation-openai
RUN pip install --no-cache-dir opentelemetry-exporter-otlp-proto-grpc
RUN pip install --no-cache-dir opentelemetry-exporter-zipkin
RUN pip install --no-cache-dir opentelemetry-exporter-zipkin-json
RUN pip install --no-cache-dir opentelemetry-exporter-zipkin-proto-http

RUN pip install --no-cache-dir opentelemetry-distro
RUN opentelemetry-bootstrap --action=install

COPY python/openai-call.py /openai-call.py