// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AckSpanProtobuf.proto

package com.ai.cloud.skywalking.protocol.proto;

public final class AckSpanProtobuf {
  private AckSpanProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AckSpanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AckSpan)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string traceId = 1;</code>
     */
    boolean hasTraceId();
    /**
     * <code>required string traceId = 1;</code>
     */
    java.lang.String getTraceId();
    /**
     * <code>required string traceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTraceIdBytes();

    /**
     * <code>optional string parentLevel = 2;</code>
     */
    boolean hasParentLevel();
    /**
     * <code>optional string parentLevel = 2;</code>
     */
    java.lang.String getParentLevel();
    /**
     * <code>optional string parentLevel = 2;</code>
     */
    com.google.protobuf.ByteString
        getParentLevelBytes();

    /**
     * <code>optional int32 levelId = 3;</code>
     */
    boolean hasLevelId();
    /**
     * <code>optional int32 levelId = 3;</code>
     */
    int getLevelId();

    /**
     * <code>required int64 cost = 4;</code>
     */
    boolean hasCost();
    /**
     * <code>required int64 cost = 4;</code>
     */
    long getCost();

    /**
     * <code>required int32 statusCode = 5;</code>
     */
    boolean hasStatusCode();
    /**
     * <code>required int32 statusCode = 5;</code>
     */
    int getStatusCode();

    /**
     * <code>optional string exceptionStack = 6;</code>
     */
    boolean hasExceptionStack();
    /**
     * <code>optional string exceptionStack = 6;</code>
     */
    java.lang.String getExceptionStack();
    /**
     * <code>optional string exceptionStack = 6;</code>
     */
    com.google.protobuf.ByteString
        getExceptionStackBytes();
  }
  /**
   * Protobuf type {@code AckSpan}
   */
  public static final class AckSpan extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AckSpan)
      AckSpanOrBuilder {
    // Use AckSpan.newBuilder() to construct.
    private AckSpan(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AckSpan(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AckSpan defaultInstance;
    public static AckSpan getDefaultInstance() {
      return defaultInstance;
    }

    public AckSpan getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AckSpan(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              traceId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              parentLevel_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              levelId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              cost_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              statusCode_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              exceptionStack_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.internal_static_AckSpan_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.internal_static_AckSpan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan.class, com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan.Builder.class);
    }

    public static com.google.protobuf.Parser<AckSpan> PARSER =
        new com.google.protobuf.AbstractParser<AckSpan>() {
      public AckSpan parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckSpan(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AckSpan> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRACEID_FIELD_NUMBER = 1;
    private java.lang.Object traceId_;
    /**
     * <code>required string traceId = 1;</code>
     */
    public boolean hasTraceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string traceId = 1;</code>
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          traceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string traceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARENTLEVEL_FIELD_NUMBER = 2;
    private java.lang.Object parentLevel_;
    /**
     * <code>optional string parentLevel = 2;</code>
     */
    public boolean hasParentLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string parentLevel = 2;</code>
     */
    public java.lang.String getParentLevel() {
      java.lang.Object ref = parentLevel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parentLevel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string parentLevel = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParentLevelBytes() {
      java.lang.Object ref = parentLevel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVELID_FIELD_NUMBER = 3;
    private int levelId_;
    /**
     * <code>optional int32 levelId = 3;</code>
     */
    public boolean hasLevelId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 levelId = 3;</code>
     */
    public int getLevelId() {
      return levelId_;
    }

    public static final int COST_FIELD_NUMBER = 4;
    private long cost_;
    /**
     * <code>required int64 cost = 4;</code>
     */
    public boolean hasCost() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 cost = 4;</code>
     */
    public long getCost() {
      return cost_;
    }

    public static final int STATUSCODE_FIELD_NUMBER = 5;
    private int statusCode_;
    /**
     * <code>required int32 statusCode = 5;</code>
     */
    public boolean hasStatusCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 statusCode = 5;</code>
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int EXCEPTIONSTACK_FIELD_NUMBER = 6;
    private java.lang.Object exceptionStack_;
    /**
     * <code>optional string exceptionStack = 6;</code>
     */
    public boolean hasExceptionStack() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string exceptionStack = 6;</code>
     */
    public java.lang.String getExceptionStack() {
      java.lang.Object ref = exceptionStack_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exceptionStack_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exceptionStack = 6;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionStackBytes() {
      java.lang.Object ref = exceptionStack_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exceptionStack_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      traceId_ = "";
      parentLevel_ = "";
      levelId_ = 0;
      cost_ = 0L;
      statusCode_ = 0;
      exceptionStack_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTraceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatusCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTraceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getParentLevelBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, levelId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, cost_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, statusCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getExceptionStackBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTraceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getParentLevelBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, levelId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, cost_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, statusCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getExceptionStackBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AckSpan}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AckSpan)
        com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.internal_static_AckSpan_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.internal_static_AckSpan_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan.class, com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan.Builder.class);
      }

      // Construct using com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        traceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        parentLevel_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        levelId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        cost_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        statusCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        exceptionStack_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.internal_static_AckSpan_descriptor;
      }

      public com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan getDefaultInstanceForType() {
        return com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan.getDefaultInstance();
      }

      public com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan build() {
        com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan buildPartial() {
        com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan result = new com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.traceId_ = traceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parentLevel_ = parentLevel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.levelId_ = levelId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cost_ = cost_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.statusCode_ = statusCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.exceptionStack_ = exceptionStack_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan) {
          return mergeFrom((com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan other) {
        if (other == com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan.getDefaultInstance()) return this;
        if (other.hasTraceId()) {
          bitField0_ |= 0x00000001;
          traceId_ = other.traceId_;
          onChanged();
        }
        if (other.hasParentLevel()) {
          bitField0_ |= 0x00000002;
          parentLevel_ = other.parentLevel_;
          onChanged();
        }
        if (other.hasLevelId()) {
          setLevelId(other.getLevelId());
        }
        if (other.hasCost()) {
          setCost(other.getCost());
        }
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasExceptionStack()) {
          bitField0_ |= 0x00000020;
          exceptionStack_ = other.exceptionStack_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTraceId()) {
          
          return false;
        }
        if (!hasCost()) {
          
          return false;
        }
        if (!hasStatusCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ai.cloud.skywalking.protocol.proto.AckSpanProtobuf.AckSpan) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object traceId_ = "";
      /**
       * <code>required string traceId = 1;</code>
       */
      public boolean hasTraceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string traceId = 1;</code>
       */
      public java.lang.String getTraceId() {
        java.lang.Object ref = traceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            traceId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string traceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTraceIdBytes() {
        java.lang.Object ref = traceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string traceId = 1;</code>
       */
      public Builder setTraceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string traceId = 1;</code>
       */
      public Builder clearTraceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        traceId_ = getDefaultInstance().getTraceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string traceId = 1;</code>
       */
      public Builder setTraceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        traceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parentLevel_ = "";
      /**
       * <code>optional string parentLevel = 2;</code>
       */
      public boolean hasParentLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string parentLevel = 2;</code>
       */
      public java.lang.String getParentLevel() {
        java.lang.Object ref = parentLevel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parentLevel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parentLevel = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParentLevelBytes() {
        java.lang.Object ref = parentLevel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentLevel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parentLevel = 2;</code>
       */
      public Builder setParentLevel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parentLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parentLevel = 2;</code>
       */
      public Builder clearParentLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parentLevel_ = getDefaultInstance().getParentLevel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parentLevel = 2;</code>
       */
      public Builder setParentLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parentLevel_ = value;
        onChanged();
        return this;
      }

      private int levelId_ ;
      /**
       * <code>optional int32 levelId = 3;</code>
       */
      public boolean hasLevelId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 levelId = 3;</code>
       */
      public int getLevelId() {
        return levelId_;
      }
      /**
       * <code>optional int32 levelId = 3;</code>
       */
      public Builder setLevelId(int value) {
        bitField0_ |= 0x00000004;
        levelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 levelId = 3;</code>
       */
      public Builder clearLevelId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        levelId_ = 0;
        onChanged();
        return this;
      }

      private long cost_ ;
      /**
       * <code>required int64 cost = 4;</code>
       */
      public boolean hasCost() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 cost = 4;</code>
       */
      public long getCost() {
        return cost_;
      }
      /**
       * <code>required int64 cost = 4;</code>
       */
      public Builder setCost(long value) {
        bitField0_ |= 0x00000008;
        cost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 cost = 4;</code>
       */
      public Builder clearCost() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cost_ = 0L;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>required int32 statusCode = 5;</code>
       */
      public boolean hasStatusCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 statusCode = 5;</code>
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>required int32 statusCode = 5;</code>
       */
      public Builder setStatusCode(int value) {
        bitField0_ |= 0x00000010;
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 statusCode = 5;</code>
       */
      public Builder clearStatusCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object exceptionStack_ = "";
      /**
       * <code>optional string exceptionStack = 6;</code>
       */
      public boolean hasExceptionStack() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string exceptionStack = 6;</code>
       */
      public java.lang.String getExceptionStack() {
        java.lang.Object ref = exceptionStack_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exceptionStack_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exceptionStack = 6;</code>
       */
      public com.google.protobuf.ByteString
          getExceptionStackBytes() {
        java.lang.Object ref = exceptionStack_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exceptionStack_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exceptionStack = 6;</code>
       */
      public Builder setExceptionStack(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        exceptionStack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exceptionStack = 6;</code>
       */
      public Builder clearExceptionStack() {
        bitField0_ = (bitField0_ & ~0x00000020);
        exceptionStack_ = getDefaultInstance().getExceptionStack();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exceptionStack = 6;</code>
       */
      public Builder setExceptionStackBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        exceptionStack_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AckSpan)
    }

    static {
      defaultInstance = new AckSpan(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AckSpan)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AckSpan_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AckSpan_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AckSpanProtobuf.proto\"z\n\007AckSpan\022\017\n\007tr" +
      "aceId\030\001 \002(\t\022\023\n\013parentLevel\030\002 \001(\t\022\017\n\007leve" +
      "lId\030\003 \001(\005\022\014\n\004cost\030\004 \002(\003\022\022\n\nstatusCode\030\005 " +
      "\002(\005\022\026\n\016exceptionStack\030\006 \001(\tB(\n&com.ai.cl" +
      "oud.skywalking.protocol.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AckSpan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AckSpan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AckSpan_descriptor,
        new java.lang.String[] { "TraceId", "ParentLevel", "LevelId", "Cost", "StatusCode", "ExceptionStack", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
