/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.apache.skywalking.oap.meter.analyzer.v2;

import java.util.List;

/**
 * Metrics rules convert to meter system.
 */
public interface MetricRuleConfig {

    /**
     * Get metrics name prefix
     */
    String getMetricPrefix();

    /**
     * Get MAL expression suffix
     */
    String getExpSuffix();

    /**
     * Get MAL expression prefix
     */
    String getExpPrefix();

    /**
     * Get all rules
     */
    List<? extends RuleConfig> getMetricsRules();

    String getFilter();

    /**
     * Returns the source name of this config (e.g., YAML file name without extension).
     * Used to build informative {@code SourceFile} attributes in generated bytecode
     * so stack traces show the originating config file.
     *
     * @return source name, or {@code null} if unknown.
     */
    /**
     * Full rule-file path for stack frames, e.g. {@code otel-rules/vm.yaml}. Defaults to the
     * source name with a {@code .yaml} extension when an implementation does not track the
     * ruleset directory.
     *
     * @return the path an operator can open, or {@code null} when unknown
     */
    default String getSourcePath() {
        return getSourceName() == null ? null : getSourceName() + ".yaml";
    }

    default String getSourceName() {
        return null;
    }

    /**
     * 1-based line of the file-level {@code filter:} key in the source YAML, or {@code 0} when
     * unknown. A compiled MAL expression splices up to three separate source locations together,
     * so each needs its own anchor; see {@link org.apache.skywalking.oap.server.core.dsl.DslYamlLineIndex}.
     *
     * @return the filter's line, or {@code 0}
     */
    default int getFilterLine() {
        return 0;
    }

    /**
     * @return 1-based line of the file-level {@code expPrefix:} key, or {@code 0} when unknown
     */
    default int getExpPrefixLine() {
        return 0;
    }

    /**
     * @return 1-based line of the file-level {@code expSuffix:} key, or {@code 0} when unknown
     */
    default int getExpSuffixLine() {
        return 0;
    }

    interface RuleConfig {
        /**
         * Get definition metrics name
         */
        String getName();

        /**
         * Build metrics MAL
         */
        String getExp();

        /**
         * 1-based line of this rule's entry (its {@code - name:} anchor) in the source YAML, or
         * {@code 0} when unknown. Used as the provenance label in the generated class name.
         *
         * @return the entry's line, or {@code 0}
         */
        default int getLineNo() {
            return 0;
        }

        /**
         * @return 1-based line of this rule's {@code exp:} key, or {@code 0} when unknown
         */
        default int getExpLine() {
            return 0;
        }
    }
}
