/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

[
  {
    "id":"d94d8ee6-0e05-4b4d-a6c2-2bc436de4322",
    "configuration":{
      "children":[
        {
          "x":0,
          "y":0,
          "w":24,
          "h":43,
          "i":"30",
          "type":"Tab",
          "children":[
            {
              "name":"TCP",
              "children":[
                {
                  "x":0,
                  "y":0,
                  "w":6,
                  "h":11,
                  "i":"0",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_write_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP Per Minute (client)",
                    "name":"write_per_minute_client"
                  },
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":12,
                  "y":0,
                  "w":6,
                  "h":11,
                  "i":"1",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_write_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP Per Minute (server)",
                    "name":"write_per_minute_server"
                  },
                  "associate":[
                    {
                      "widgetId":"0"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":0,
                  "y":33,
                  "w":6,
                  "h":11,
                  "i":"2",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_read_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Read OP Per Minute (client)",
                    "name":"read_per_minute_server"
                  },
                  "associate":[
                    {
                      "widgetId":"3"
                    },
                    {
                      "widgetId":"5"
                    },
                    {
                      "widgetId":"7"
                    },
                    {
                      "widgetId":"9"
                    },
                    {
                      "widgetId":"11"
                    },
                    {
                      "widgetId":"24"
                    },
                    {
                      "widgetId":"25"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"24"
                  }
                },
                {
                  "x":12,
                  "y":33,
                  "w":6,
                  "h":11,
                  "i":"3",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_read_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Read OP Per Minute (server)"
                  },
                  "associate":[
                    {
                      "widgetId":"2"
                    },
                    {
                      "widgetId":"5"
                    },
                    {
                      "widgetId":"7"
                    },
                    {
                      "widgetId":"9"
                    },
                    {
                      "widgetId":"11"
                    },
                    {
                      "widgetId":"24"
                    },
                    {
                      "widgetId":"25"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"24"
                  }
                },
                {
                  "x":6,
                  "y":0,
                  "w":6,
                  "h":11,
                  "i":"4",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_write_total_bytes"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write Package Size (Client) (KB)",
                    "name":"write_package_size_client"
                  },
                  "metricConfig":[
                    {
                      "unit":"KB",
                      "calculation":"byteToKB"
                    }
                  ],
                  "associate":[

                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":6,
                  "y":33,
                  "w":6,
                  "h":11,
                  "i":"5",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_read_total_bytes"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Read Package Size (Client) (KB)",
                    "name":"read_package_szie_client"
                  },
                  "metricConfig":[
                    {
                      "unit":"KB",
                      "calculation":"byteToKB"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"2"
                    },
                    {
                      "widgetId":"3"
                    },
                    {
                      "widgetId":"7"
                    },
                    {
                      "widgetId":"9"
                    },
                    {
                      "widgetId":"11"
                    },
                    {
                      "widgetId":"24"
                    },
                    {
                      "widgetId":"25"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"24"
                  }
                },
                {
                  "x":18,
                  "y":0,
                  "w":6,
                  "h":11,
                  "i":"6",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_write_total_bytes"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "metricConfig":[
                    {
                      "unit":"KB",
                      "calculation":"byteToKB"
                    }
                  ],
                  "widget":{
                    "title":"Write Package Size (Server) (KB)",
                    "name":"write_package_size_server"
                  },
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"0"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":18,
                  "y":33,
                  "w":6,
                  "h":11,
                  "i":"7",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_read_total_bytes"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "metricConfig":[
                    {
                      "unit":"KB",
                      "calculation":"byteToKB"
                    }
                  ],
                  "widget":{
                    "title":"Read Package Size (Server) (KB)",
                    "name":"read_package_size_server"
                  },
                  "associate":[
                    {
                      "widgetId":"2"
                    },
                    {
                      "widgetId":"5"
                    },
                    {
                      "widgetId":"3"
                    },
                    {
                      "widgetId":"9"
                    },
                    {
                      "widgetId":"11"
                    },
                    {
                      "widgetId":"24"
                    },
                    {
                      "widgetId":"25"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"24"
                  }
                },
                {
                  "x":0,
                  "y":11,
                  "w":6,
                  "h":11,
                  "i":"8",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_write_avg_exe_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP Avg Time (Client) (ms)",
                    "name":"write_avg_time_client"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond",
                      "unit":"ms"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"0"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"4"
                  }
                },
                {
                  "x":0,
                  "y":44,
                  "w":6,
                  "h":11,
                  "i":"9",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_read_avg_exe_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Read OP Avg Time (Client) (ms)",
                    "name":"read_avg_time_client"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond",
                      "unit":"ms"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"2"
                    },
                    {
                      "widgetId":"5"
                    },
                    {
                      "widgetId":"7"
                    },
                    {
                      "widgetId":"3"
                    },
                    {
                      "widgetId":"11"
                    },
                    {
                      "widgetId":"24"
                    },
                    {
                      "widgetId":"25"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"24"
                  }
                },
                {
                  "x":12,
                  "y":11,
                  "w":6,
                  "h":11,
                  "i":"10",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_write_avg_exe_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP Avg Time (Server) (ms)",
                    "name":"write_avg_time_server"
                  },
                  "metricConfig":[
                    {
                      "unit":"ms",
                      "calculation":"nanosecondToMillisecond"
                    }
                  ],
                  "associate":[

                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":12,
                  "y":44,
                  "w":6,
                  "h":11,
                  "i":"11",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_read_avg_exe_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Read OP Avg Time (Server) (ms)",
                    "name":"read_avg_time_server"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond",
                      "unit":"ms"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"2"
                    },
                    {
                      "widgetId":"5"
                    },
                    {
                      "widgetId":"7"
                    },
                    {
                      "widgetId":"9"
                    },
                    {
                      "widgetId":"3"
                    },
                    {
                      "widgetId":"24"
                    },
                    {
                      "widgetId":"25"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"24"
                  }
                },
                {
                  "x":0,
                  "y":55,
                  "w":6,
                  "h":11,
                  "i":"12",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_connect_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Connect OP Per Minute (client)",
                    "name":"connect_per_minute_client"
                  },
                  "associate":[
                    {
                      "widgetId":"13"
                    },
                    {
                      "widgetId":"14"
                    },
                    {
                      "widgetId":"15"
                    }
                  ]
                },
                {
                  "x":6,
                  "y":55,
                  "w":6,
                  "h":11,
                  "i":"13",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_connect_exe_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Connect Avg Time (Client) (ms)",
                    "name":"connect_avg_time_client"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond",
                      "unit":"ms"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"12"
                    },
                    {
                      "widgetId":"14"
                    },
                    {
                      "widgetId":"15"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"12"
                  }
                },
                {
                  "x":12,
                  "y":55,
                  "w":6,
                  "h":11,
                  "i":"14",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_connect_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Connect OP Per Minute (server)",
                    "name":"connect_per_minute_server"
                  },
                  "associate":[
                    {
                      "widgetId":"13"
                    },
                    {
                      "widgetId":"12"
                    },
                    {
                      "widgetId":"15"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"12"
                  }
                },
                {
                  "x":18,
                  "y":55,
                  "w":6,
                  "h":11,
                  "i":"15",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_connect_avg_exe_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Connect Avg Time (Server) (ms)",
                    "name":"connect_avg_time_server"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond",
                      "unit":"ms"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"13"
                    },
                    {
                      "widgetId":"14"
                    },
                    {
                      "widgetId":"12"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"12"
                  }
                },
                {
                  "x":0,
                  "y":66,
                  "w":6,
                  "h":11,
                  "i":"16",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_close_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Close OP Per Minute (client)",
                    "name":"close_per_minute_client"
                  },
                  "associate":[
                    {
                      "widgetId":"17"
                    },
                    {
                      "widgetId":"18"
                    },
                    {
                      "widgetId":"19"
                    }
                  ]
                },
                {
                  "x":6,
                  "y":66,
                  "w":6,
                  "h":11,
                  "i":"17",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_close_avg_exe_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Close Avg Time (Client) (ms)",
                    "name":"close_avg_time_client"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond",
                      "unit":"ms"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"16"
                    },
                    {
                      "widgetId":"18"
                    },
                    {
                      "widgetId":"19"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"16"
                  }
                },
                {
                  "x":12,
                  "y":66,
                  "w":6,
                  "h":11,
                  "i":"18",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_close_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Close OP Per Minute (server)",
                    "name":"close_per_minute_server"
                  },
                  "associate":[
                    {
                      "widgetId":"17"
                    },
                    {
                      "widgetId":"16"
                    },
                    {
                      "widgetId":"19"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"16"
                  }
                },
                {
                  "x":18,
                  "y":66,
                  "w":6,
                  "h":11,
                  "i":"19",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_close_avg_exe_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Close Avg Time (Server) (ms)",
                    "name":"close_avg_time_server"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond",
                      "unit":"ms"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"17"
                    },
                    {
                      "widgetId":"18"
                    },
                    {
                      "widgetId":"16"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"16"
                  }
                },
                {
                  "x":6,
                  "y":22,
                  "w":6,
                  "h":11,
                  "i":"20",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_write_rtt_time_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP RTT Percentile (client) (microsecond)",
                    "name":"write_rtt_percentile_client"
                  },
                  "metricConfig":[
                    {
                      "unit":"ns"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"0"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":18,
                  "y":22,
                  "w":6,
                  "h":11,
                  "i":"21",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_write_rtt_time_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP RTT Percentile (server) (microsecond)",
                    "name":"write_rtt_percentile_server"
                  },
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"0"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":6,
                  "y":11,
                  "w":6,
                  "h":11,
                  "i":"22",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_write_exe_time_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP Exe Time Percentile (client) (ms)",
                    "name":"write_exe_time_percentile_client"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"0"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":18,
                  "y":11,
                  "w":6,
                  "h":11,
                  "i":"23",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_write_exe_time_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP Exe Time Percentile (server) (ms)",
                    "name":"write_exe_time_percentile_server"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"0"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":6,
                  "y":44,
                  "w":6,
                  "h":11,
                  "i":"24",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_read_exe_time_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Read OP Exe Time Percentile (client) (ms)",
                    "name":"read_exe_time_percentile_client"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"2"
                    },
                    {
                      "widgetId":"5"
                    },
                    {
                      "widgetId":"7"
                    },
                    {
                      "widgetId":"9"
                    },
                    {
                      "widgetId":"11"
                    },
                    {
                      "widgetId":"3"
                    },
                    {
                      "widgetId":"25"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"5"
                  }
                },
                {
                  "x":18,
                  "y":44,
                  "w":6,
                  "h":11,
                  "i":"25",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_read_exe_time_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Read OP Exe Time Percentile (server) (ms)",
                    "name":"read_exe_time_percentile_server"
                  },
                  "metricConfig":[
                    {
                      "calculation":"nanosecondToMillisecond"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"2"
                    },
                    {
                      "widgetId":"5"
                    },
                    {
                      "widgetId":"7"
                    },
                    {
                      "widgetId":"9"
                    },
                    {
                      "widgetId":"11"
                    },
                    {
                      "widgetId":"24"
                    },
                    {
                      "widgetId":"3"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"24"
                  }
                },
                {
                  "x":0,
                  "y":22,
                  "w":6,
                  "h":11,
                  "i":"28",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_client_write_avg_rtt_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP Avg RTT (Client) (microsecond)",
                    "name":"write_avg_rtt_client"
                  },
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"0"
                    },
                    {
                      "widgetId":"29"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                },
                {
                  "x":12,
                  "y":22,
                  "w":6,
                  "h":11,
                  "i":"29",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_server_write_avg_rtt_time"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Write OP Avg RTT (Server) (microsecond)",
                    "name":"write_avg_rtt_server"
                  },
                  "associate":[
                    {
                      "widgetId":"1"
                    },
                    {
                      "widgetId":"4"
                    },
                    {
                      "widgetId":"6"
                    },
                    {
                      "widgetId":"8"
                    },
                    {
                      "widgetId":"10"
                    },
                    {
                      "widgetId":"20"
                    },
                    {
                      "widgetId":"21"
                    },
                    {
                      "widgetId":"22"
                    },
                    {
                      "widgetId":"23"
                    },
                    {
                      "widgetId":"28"
                    },
                    {
                      "widgetId":"0"
                    }
                  ],
                  "filters":{
                    "dataIndex":9,
                    "sourceId":"8"
                  }
                }
              ]
            },
            {
              "name":"HTTP/1.x",
              "children":[
                {
                  "x":0,
                  "y":0,
                  "w":12,
                  "h":11,
                  "i":"0",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_request_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Request CPM",
                    "name":"http1-request-cpm"
                  },
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                },
                {
                  "x":12,
                  "y":0,
                  "w":12,
                  "h":11,
                  "i":"1",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_response_status_cpm"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"HTTP Response CPM",
                    "name":"http1-response-cpm"
                  },
                  "associate":[
                    {
                      "widgetId":"30-1-0"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":4,
                    "sourceId":"30-1-6"
                  }
                },
                {
                  "x":0,
                  "y":11,
                  "w":6,
                  "h":11,
                  "i":"2",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_request_package_size"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Request Package Avg Size (KB)",
                    "name":"http1-request-package-avg-size"
                  },
                  "metricConfig":[
                    {
                      "calculation":"byteToKB"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-0"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                },
                {
                  "x":12,
                  "y":11,
                  "w":6,
                  "h":11,
                  "i":"3",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_response_package_size"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Response Package Avg Size (KB)",
                    "name":"http1-response-package-avg-size"
                  },
                  "metricConfig":[
                    {
                      "calculation":"byteToKB"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-0"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                },
                {
                  "x":6,
                  "y":11,
                  "w":6,
                  "h":11,
                  "i":"4",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_request_package_size_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Request Package Size Percentile (KB)",
                    "name":"http1-request-package-size-percentile"
                  },
                  "metricConfig":[
                    {
                      "calculation":"byteToKB"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-0"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                },
                {
                  "x":18,
                  "y":11,
                  "w":6,
                  "h":11,
                  "i":"5",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_response_package_size_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Response Package Size Percentile (KB)",
                    "name":"http1-response-package-size-percentile"
                  },
                  "metricConfig":[
                    {
                      "calculation":"byteToKB"
                    }
                  ],
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-0"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                },
                {
                  "x":0,
                  "y":22,
                  "w":6,
                  "h":11,
                  "i":"6",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_client_duration"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Response Avg Duration (client) (ms)",
                    "name":"http1-resposne-avg-duration-client"
                  },
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-0"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                },
                {
                  "x":6,
                  "y":22,
                  "w":6,
                  "h":11,
                  "i":"7",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_client_duration_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Response Duration Percentile (client) (ms)",
                    "name":"http1-response-duration-percentile-client"
                  },
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-0"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                },
                {
                  "x":12,
                  "y":22,
                  "w":6,
                  "h":11,
                  "i":"8",
                  "type":"Widget",
                  "metricTypes":[
                    "readMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_server_duration"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Response Avg Duration (server) (ms)",
                    "name":"http1-response-avg-duration-server"
                  },
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-0"
                    },
                    {
                      "widgetId":"30-1-9"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                },
                {
                  "x":18,
                  "y":22,
                  "w":6,
                  "h":11,
                  "i":"9",
                  "type":"Widget",
                  "metricTypes":[
                    "readLabeledMetricsValues"
                  ],
                  "metrics":[
                    "process_relation_http1_server_duration_percentile"
                  ],
                  "graph":{
                    "type":"Line",
                    "step":false,
                    "smooth":false,
                    "showSymbol":false,
                    "showXAxis":true,
                    "showYAxis":true
                  },
                  "widget":{
                    "title":"Response Duration Percentile (server) (ms)",
                    "name":"http1-response-duration-percentile-server"
                  },
                  "associate":[
                    {
                      "widgetId":"30-1-1"
                    },
                    {
                      "widgetId":"30-1-2"
                    },
                    {
                      "widgetId":"30-1-3"
                    },
                    {
                      "widgetId":"30-1-4"
                    },
                    {
                      "widgetId":"30-1-5"
                    },
                    {
                      "widgetId":"30-1-6"
                    },
                    {
                      "widgetId":"30-1-7"
                    },
                    {
                      "widgetId":"30-1-8"
                    },
                    {
                      "widgetId":"30-1-0"
                    }
                  ],
                  "filters":{
                    "dataIndex":8,
                    "sourceId":"30-1-1"
                  }
                }
              ]
            },
            {
              "name":"HTTP Requests",
              "children":[
                {
                  "x":0,
                  "y":2,
                  "w":8,
                  "h":37,
                  "i":"0",
                  "type":"Widget",
                  "metricTypes":[
                    "readRecords"
                  ],
                  "metrics":[
                    "sampled_slow_trace_record"
                  ],
                  "graph":{
                    "type":"TopList",
                    "color":"purple"
                  },
                  "widget":{
                    "title":"Sampled Slow Traces(ms)"
                  },
                  "metricConfig":[
                    {
                      "topN":"50"
                    }
                  ]
                },
                {
                  "x":8,
                  "y":2,
                  "w":8,
                  "h":37,
                  "i":"1",
                  "type":"Widget",
                  "metricTypes":[
                    "readRecords"
                  ],
                  "metrics":[
                    "sampled_status_4xx_trace_record"
                  ],
                  "graph":{
                    "type":"TopList",
                    "color":"purple"
                  },
                  "widget":{
                    "title":"Traces from HTTP Code in [400, 500) (ms)"
                  },
                  "metricConfig":[
                    {
                      "topN":"50"
                    }
                  ]
                },
                {
                  "x":16,
                  "y":2,
                  "w":8,
                  "h":37,
                  "i":"2",
                  "type":"Widget",
                  "metricTypes":[
                    "readRecords"
                  ],
                  "metrics":[
                    "sampled_status_5xx_trace_record"
                  ],
                  "graph":{
                    "type":"TopList",
                    "color":"purple"
                  },
                  "widget":{
                    "title":"Traces from HTTP Code in [500, 600) (ms)"
                  },
                  "metricConfig":[
                    {
                      "topN":"50"
                    }
                  ]
                },
                {
                  "x":0,
                  "y":0,
                  "w":24,
                  "h":2,
                  "i":"3",
                  "type":"Text",
                  "graph":{
                    "fontColor":"white",
                    "backgroundColor":"blue",
                    "content":"The sampled HTTP 1.x requests within tracing context.",
                    "fontSize":14,
                    "textAlign":"left"
                  }
                }
              ]
            }
          ]
        }
      ],
      "layer":"MESH_DP",
      "entity":"ProcessRelation",
      "name":"ServiceMesh-Data-Plane-Process-Relation-Metrics",
      "id":"d94d8ee6-0e05-4b4d-a6c2-2bc436de4322",
      "isRoot":false
    }
  }
]