/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.apache.skywalking.oal.v2.generator;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtMethod;
import javassist.bytecode.AttributeInfo;
import javassist.bytecode.CodeAttribute;
import javassist.bytecode.SourceFileAttribute;
import org.apache.skywalking.oal.v2.model.MetricDefinition;
import org.apache.skywalking.oal.v2.parser.OALScriptParserV2;
import org.apache.skywalking.oap.server.core.analysis.Stream;
import org.apache.skywalking.oap.server.core.dsl.DslGeneratedFileWriter;
import org.apache.skywalking.oap.server.core.oal.rt.OALDefine;
import org.apache.skywalking.oap.server.core.source.DefaultScopeDefine;
import org.apache.skywalking.oap.server.core.source.Service;
import org.apache.skywalking.oap.server.core.storage.StorageBuilderFactory;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Asserts what OAL actually stamps into its generated bytecode, by reading the attributes back off
 * the {@code CtClass}es the generator produced.
 *
 * <p>OAL is the one DSL whose method bodies come from FreeMarker templates rather than from its own
 * codegen, so {@link DslGeneratedFileWriter#lineOfMethod} has to locate a declaration it did not
 * write. A miss there is silent by design — {@code attachSignatureLine} returns early on a
 * non-positive line rather than throwing, because a missing line must never stop a metric from
 * compiling. Every other OAL test would stay green with the attribute absent, so without this the
 * next template edit could drop attribution for a whole method and nothing would say so.
 */
class OALSourceAttributionTest {

    private static final String SOURCE_PACKAGE = "org.apache.skywalking.oap.server.core.source.";
    private static final String METRICS_PACKAGE =
        "org.apache.skywalking.oap.server.core.source.oal.rt.metrics.";

    private static final String OAL_FILE = "attribution-probe.oal";

    /**
     * Line numbers are the assertion, so they are pinned here rather than searched for. Metric
     * names are unique to this test: the metrics package and the class loader are shared with
     * every other OAL test in the fork.
     */
    private static final String OAL =
        "attrprobe_service_calls = from(Service.*).count();\n"          // 1
            + "\n"                                                     // 2
            + "attrprobe_service_resp_time = from(Service.latency).longAvg();\n"; // 3

    private static final int CALLS_LINE = 1;
    private static final int RESP_TIME_LINE = 3;

    /**
     * The methods OAL renders from FreeMarker templates, restated here so the contract is pinned
     * rather than read back from whatever production happens to emit. These are the method names,
     * not the template file names: metrics/id.ftl declares id0().
     *
     * <p>Field accessors are excluded deliberately: Javassist synthesises them from the field
     * declarations, so they have no signature in the generated source and no line to point at. The
     * class-level coordinate still names their rule.
     */
    private static final Set<String> TEMPLATED_METHODS = new HashSet<>(Arrays.asList(
        "id0", "hashCode", "remoteHashCode", "equals", "serialize", "deserialize",
        "getMeta", "toHour", "toDay", "appendDebugFields"));

    private static ClassPool CLASS_POOL;
    private static List<Class> METRICS_CLASSES;
    private static List<Class> DISPATCHER_CLASSES;

    @BeforeAll
    static void generate() throws Exception {
        try {
            new DefaultScopeDefine.Listener().notify(Service.class);
        } catch (RuntimeException ignored) {
            // Already registered by another test in this fork.
        }

        // A catalog of its own gives this test its own dispatcher package, so generating a Service
        // dispatcher here cannot collide with the ones the other OAL tests define.
        final OALDefine define =
            new OALDefine(OAL_FILE, "org.apache.skywalking.oap.server.core.source", "AttrProbe") {
            };

        CLASS_POOL = ClassPool.getDefault();
        final OALClassGeneratorV2 generator = new OALClassGeneratorV2(define, CLASS_POOL);
        generator.setStorageBuilderFactory(new StorageBuilderFactory.Default());

        final OALScriptParserV2 parser = OALScriptParserV2.parse(OAL, OAL_FILE);
        final MetricDefinitionEnricher enricher =
            new MetricDefinitionEnricher(SOURCE_PACKAGE, METRICS_PACKAGE);
        final List<CodeGenModel> models = new ArrayList<>();
        for (final MetricDefinition metric : parser.getMetrics()) {
            models.add(enricher.enrich(metric));
        }

        METRICS_CLASSES = new ArrayList<>();
        DISPATCHER_CLASSES = new ArrayList<>();
        generator.generateClassAtRuntime(
            models, parser.getDisabledSources(), METRICS_CLASSES, DISPATCHER_CLASSES);

        assertEquals(2, METRICS_CLASSES.size());
        assertEquals(1, DISPATCHER_CLASSES.size(), "both metrics share the Service scope");
    }

    private static CtClass ct(final Class<?> loaded) throws Exception {
        // OAL never detaches, so the pool still holds the instance the generator stamped.
        return CLASS_POOL.get(loaded.getName());
    }

    private static String sourceFileOf(final CtClass ctClass) {
        final SourceFileAttribute attr = (SourceFileAttribute)
            ctClass.getClassFile2().getAttribute(SourceFileAttribute.tag);
        assertNotNull(attr, "no SourceFile on " + ctClass.getName());
        return attr.getFileName();
    }

    /**
     * {@code attachSignatureLine} writes the table as raw bytes, so it comes back as a plain
     * {@link AttributeInfo} rather than a parsed {@code LineNumberAttribute}.
     *
     * @param method the generated method to inspect
     * @return the single line the method is attributed to, or {@code -1} when it carries no table
     */
    private static int soleLineOf(final CtMethod method) {
        final CodeAttribute code = method.getMethodInfo2().getCodeAttribute();
        if (code == null) {
            return -1;
        }
        final AttributeInfo table = code.getAttribute("LineNumberTable");
        if (table == null) {
            return -1;
        }
        final byte[] bytes = table.get();
        assertEquals(6, bytes.length, "expected exactly one entry in " + method.getName());
        assertEquals(1, ((bytes[0] & 0xff) << 8) | (bytes[1] & 0xff),
            "expected exactly one entry in " + method.getName());
        return ((bytes[4] & 0xff) << 8) | (bytes[5] & 0xff);
    }

    private static CtClass metricsOf(final String namePart) throws Exception {
        for (final Class<?> clazz : METRICS_CLASSES) {
            if (clazz.getSimpleName().contains(namePart)) {
                return ct(clazz);
            }
        }
        throw new AssertionError("no generated metrics class matching " + namePart);
    }

    @Test
    void eachMetricsClassNamesTheOalFileAndItsOwnStatementLine() throws Exception {
        final CtClass calls = metricsOf("Calls");
        final CtClass respTime = metricsOf("RespTime");

        // The .java exists only under SW_DYNAMIC_CLASS_ENGINE_DEBUG, so the rule leads: in a
        // production stack frame the OAL file and line are the only resolvable coordinate.
        assertEquals("(" + OAL_FILE + ":" + CALLS_LINE + ")" + calls.getSimpleName() + ".java",
            sourceFileOf(calls));
        assertEquals(
            "(" + OAL_FILE + ":" + RESP_TIME_LINE + ")" + respTime.getSimpleName() + ".java",
            sourceFileOf(respTime));
    }

    @Test
    void theDispatcherNamesTheOalFileWithoutALine() throws Exception {
        final CtClass dispatcher = ct(DISPATCHER_CLASSES.get(0));

        // One dispatcher carries every metric of the scope, so no single rule line is true for the
        // class. A line here would point every frame in the class at whichever rule happened to be
        // first.
        assertEquals("(" + OAL_FILE + ")" + dispatcher.getSimpleName() + ".java",
            sourceFileOf(dispatcher));
    }

    @Test
    void everyTemplatedMetricsMethodCarriesOneLineOfItsOwn() throws Exception {
        for (final Class<?> loaded : METRICS_CLASSES) {
            final CtClass ctClass = ct(loaded);
            final Set<Integer> seen = new HashSet<>();
            final Set<String> found = new HashSet<>();

            for (final CtMethod method : ctClass.getDeclaredMethods()) {
                if (!TEMPLATED_METHODS.contains(method.getName())) {
                    continue;
                }
                final int line = soleLineOf(method);
                assertTrue(line > 0,
                    ctClass.getSimpleName() + "." + method.getName()
                        + " carries no LineNumberTable: lineOfMethod failed to find its "
                        + "declaration, and attachSignatureLine dropped the attribute silently");
                assertTrue(line > DslGeneratedFileWriter.SOURCE_FILE_PREAMBLE_LINES,
                    "line " + line + " lands inside the generated file's preamble");
                assertTrue(seen.add(line),
                    ctClass.getSimpleName() + "." + method.getName() + " shares line " + line
                        + " with another method, so the signature lookup matched the wrong one");
                found.add(method.getName());
            }
            assertEquals(TEMPLATED_METHODS, found,
                "every templated method must be attributed in " + ctClass.getSimpleName());
        }
    }

    @Test
    void everyDispatchMethodCarriesOneLineOfItsOwn() throws Exception {
        final CtClass dispatcher = ct(DISPATCHER_CLASSES.get(0));
        final Set<Integer> seen = new HashSet<>();

        for (final CtMethod method : dispatcher.getDeclaredMethods()) {
            if (!method.getName().startsWith("do")) {
                continue;
            }
            final int line = soleLineOf(method);
            assertTrue(line > 0, method.getName() + " carries no LineNumberTable");
            assertTrue(seen.add(line),
                method.getName() + " shares line " + line + " with another do<Metric> method");
        }
        assertEquals(2, seen.size(), "one do<Metric> per rule, each on its own line");
    }

    @Test
    void theBuilderCarriesTheRuleProvenanceButNoLineNumbers() throws Exception {
        final Class<?> calls = METRICS_CLASSES.stream()
            .filter(c -> c.getSimpleName().contains("Calls"))
            .findFirst()
            .orElseThrow(() -> new AssertionError("no Calls metrics class"));
        final CtClass builder = ct(calls.getAnnotation(Stream.class).builder());

        // The builder writes no generated source file in any mode, so its own name would never
        // resolve to anything. The rule coordinate is the only part of this that a reader can act
        // on.
        assertEquals("(" + OAL_FILE + ":" + CALLS_LINE + ")" + builder.getSimpleName() + ".java",
            sourceFileOf(builder));

        for (final CtMethod method : builder.getDeclaredMethods()) {
            final CodeAttribute code = method.getMethodInfo2().getCodeAttribute();
            if (code == null) {
                continue;
            }
            assertNull(code.getAttribute("LineNumberTable"),
                builder.getSimpleName() + "." + method.getName()
                    + " claims a line in a file that is never written");
        }
    }
}
