/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.skywalking.oap.server.core.config.v2.compiler;

import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.BiFunction;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtNewConstructor;
import javassist.CtNewMethod;
import lombok.extern.slf4j.Slf4j;
import org.apache.skywalking.oap.server.core.WorkPath;
import org.apache.skywalking.oap.server.core.config.v2.compiler.hierarchy.rule.rt.HierarchyRulePackageHolder;
import org.apache.skywalking.oap.server.library.util.StringUtil;
import org.apache.skywalking.oap.server.core.query.type.Service;

/**
 * Generates {@link BiFunction BiFunction&lt;Service, Service, Boolean&gt;} implementation classes
 * from {@link HierarchyRuleModel} AST using Javassist bytecode generation.
 *
 * <p>Rule expressions are parsed from {@code hierarchy-definition.yml} {@code auto-matching-rules}
 * section. The grammar ({@code HierarchyRuleParser.g4}) supports:
 * <ul>
 *   <li>Property access on {@link Service}: {@code u.name}, {@code l.shortName}
 *       — mapped to getter methods ({@code getName()}, {@code getShortName()})
 *       via {@link #toGetter(String)}</li>
 *   <li>String method calls: {@code substring()}, {@code lastIndexOf()}, {@code concat()}</li>
 *   <li>Comparisons: {@code ==}, {@code !=} (via {@code Objects.equals()}),
 *       {@code >}, {@code <}, {@code >=}, {@code <=}</li>
 *   <li>Logical operators: {@code &&}, {@code ||}, {@code !}</li>
 *   <li>Control flow: {@code if/else}, {@code return}</li>
 *   <li>Literals: strings, numbers, booleans</li>
 * </ul>
 *
 * <p>Debugging support in generated bytecode:
 * <ul>
 *   <li><b>SourceFile</b>: set via {@link #formatSourceFileName(String)} to
 *       {@code (hierarchy-definition.yml)ruleName.java} so stack traces show the
 *       originating YAML file and rule name</li>
 *   <li><b>LineNumberTable</b>: added via {@link #addLineNumberTable} so debuggers
 *       can step through generated code</li>
 *   <li><b>LocalVariableTable</b>: added via {@link #addLocalVariableTable} with
 *       the original parameter names (e.g., {@code u}, {@code l}) for debugger
 *       variable inspection</li>
 * </ul>
 */
@Slf4j
public final class HierarchyRuleClassGenerator {

    private static final AtomicInteger CLASS_COUNTER = new AtomicInteger(0);

    private static final String PACKAGE_PREFIX =
        "org.apache.skywalking.oap.server.core.config.v2.compiler.hierarchy.rule.rt.";

    private static final java.util.Set<String> USED_CLASS_NAMES =
        java.util.Collections.synchronizedSet(new java.util.HashSet<>());

    private final ClassPool classPool;
    private File classOutputDir;
    private String classNameHint;
    private String yamlSource;

    public HierarchyRuleClassGenerator() {
        this(ClassPool.getDefault());
        if (StringUtil.isNotEmpty(System.getenv("SW_DYNAMIC_CLASS_ENGINE_DEBUG"))) {
            classOutputDir = new File(WorkPath.getPath().getParentFile(), "hierarchy-rt");
        }
    }

    public HierarchyRuleClassGenerator(final ClassPool classPool) {
        this.classPool = classPool;
    }

    public void setClassOutputDir(final File dir) {
        this.classOutputDir = dir;
    }

    public void setClassNameHint(final String hint) {
        this.classNameHint = hint;
    }

    public void setYamlSource(final String yamlSource) {
        this.yamlSource = yamlSource;
    }

    private String makeClassName(final String defaultPrefix) {
        if (classNameHint != null) {
            return dedupClassName(PACKAGE_PREFIX + buildHintedName());
        }
        return PACKAGE_PREFIX + defaultPrefix + CLASS_COUNTER.getAndIncrement();
    }

    /**
     * Builds class name from {@code yamlSource} + {@code classNameHint}.
     * Pattern: {@code {yamlBaseName}_L{lineNo}_{hint}} when yamlSource is available,
     * falls back to just {@code {hint}} otherwise.
     */
    private String buildHintedName() {
        final String hint = sanitizeName(classNameHint);
        if (yamlSource == null) {
            return hint;
        }
        String yamlBase = yamlSource;
        String lineNo = null;
        final int colonIdx = yamlSource.lastIndexOf(':');
        if (colonIdx > 0) {
            yamlBase = yamlSource.substring(0, colonIdx);
            lineNo = yamlSource.substring(colonIdx + 1);
        }
        final int dotIdx = yamlBase.lastIndexOf('.');
        if (dotIdx > 0) {
            yamlBase = yamlBase.substring(0, dotIdx);
        }
        final StringBuilder sb = new StringBuilder();
        sb.append(sanitizeName(yamlBase));
        if (lineNo != null) {
            sb.append("_L").append(lineNo);
        }
        sb.append('_').append(hint);
        return sb.toString();
    }

    private String dedupClassName(final String base) {
        if (USED_CLASS_NAMES.add(base)) {
            return base;
        }
        for (int i = 2; ; i++) {
            final String candidate = base + "_" + i;
            if (USED_CLASS_NAMES.add(candidate)) {
                return candidate;
            }
        }
    }

    private static String sanitizeName(final String name) {
        if (name == null || name.isEmpty()) {
            return "Generated";
        }
        final StringBuilder sb = new StringBuilder(name.length() + 1);
        if (!Character.isJavaIdentifierStart(name.charAt(0))) {
            sb.append('_');
        }
        for (int i = 0; i < name.length(); i++) {
            final char c = name.charAt(i);
            sb.append(Character.isJavaIdentifierPart(c) ? c : '_');
        }
        return sb.toString();
    }

    /**
     * Builds the {@code SourceFile} attribute value embedded in the generated class bytecode.
     * Format: {@code (hierarchy-definition.yml)name.java} so that stack traces show both
     * the originating YAML file and the rule name. Falls back to just {@code name.java}
     * when {@code yamlSource} is not set (e.g., in unit tests).
     */
    private String formatSourceFileName(final String ruleName) {
        final String classFile = sanitizeName(ruleName) + ".java";
        if (yamlSource != null) {
            return "(" + yamlSource + ")" + classFile;
        }
        return classFile;
    }

    private static void setSourceFile(final CtClass ctClass, final String name) {
        try {
            final javassist.bytecode.ClassFile cf = ctClass.getClassFile();
            final javassist.bytecode.AttributeInfo sf = cf.getAttribute("SourceFile");
            if (sf != null) {
                final javassist.bytecode.ConstPool cp = cf.getConstPool();
                final int idx = cp.addUtf8Info(name);
                sf.set(new byte[]{(byte) (idx >> 8), (byte) idx});
            }
        } catch (Exception e) {
            // best-effort
        }
    }

    private void addLineNumberTable(final javassist.CtMethod method,
                                     final int firstResultSlot) {
        try {
            final javassist.bytecode.MethodInfo mi = method.getMethodInfo();
            final javassist.bytecode.CodeAttribute code = mi.getCodeAttribute();
            if (code == null) {
                return;
            }

            final java.util.ArrayList<int[]> entries = new java.util.ArrayList<>();
            int line = 1;
            boolean nextIsNewLine = true;

            final javassist.bytecode.CodeIterator ci = code.iterator();
            while (ci.hasNext()) {
                final int pc = ci.next();
                if (nextIsNewLine) {
                    entries.add(new int[]{pc, line++});
                    nextIsNewLine = false;
                }
                final int op = ci.byteAt(pc) & 0xFF;
                int slot = -1;
                if (op >= 59 && op <= 78) {
                    slot = (op - 59) % 4;
                } else if (op >= 54 && op <= 58) {
                    slot = ci.byteAt(pc + 1) & 0xFF;
                }
                if (slot >= firstResultSlot) {
                    nextIsNewLine = true;
                }
            }

            if (entries.isEmpty()) {
                return;
            }

            final javassist.bytecode.ConstPool cp = mi.getConstPool();
            final byte[] info = new byte[2 + entries.size() * 4];
            info[0] = (byte) (entries.size() >> 8);
            info[1] = (byte) entries.size();
            for (int i = 0; i < entries.size(); i++) {
                final int off = 2 + i * 4;
                info[off] = (byte) (entries.get(i)[0] >> 8);
                info[off + 1] = (byte) entries.get(i)[0];
                info[off + 2] = (byte) (entries.get(i)[1] >> 8);
                info[off + 3] = (byte) entries.get(i)[1];
            }
            code.getAttributes().add(
                new javassist.bytecode.AttributeInfo(cp, "LineNumberTable", info));
        } catch (Exception e) {
            log.warn("Failed to add LineNumberTable: {}", e.getMessage());
        }
    }

    private void writeClassFile(final CtClass ctClass) {
        if (classOutputDir == null) {
            return;
        }
        if (!classOutputDir.exists()) {
            classOutputDir.mkdirs();
        }
        final File file = new File(classOutputDir, ctClass.getSimpleName() + ".class");
        try (DataOutputStream out = new DataOutputStream(new FileOutputStream(file))) {
            ctClass.toBytecode(out);
        } catch (Exception e) {
            log.warn("Failed to write class file {}: {}", file, e.getMessage());
        }
    }

    private void addLocalVariableTable(final javassist.CtMethod method,
                                       final String className,
                                       final String[][] vars) {
        try {
            final javassist.bytecode.MethodInfo mi = method.getMethodInfo();
            final javassist.bytecode.CodeAttribute code = mi.getCodeAttribute();
            if (code == null) {
                return;
            }
            final javassist.bytecode.ConstPool cp = mi.getConstPool();
            final int len = code.getCodeLength();
            final javassist.bytecode.LocalVariableAttribute lva =
                new javassist.bytecode.LocalVariableAttribute(cp);
            lva.addEntry(0, len,
                cp.addUtf8Info("this"),
                cp.addUtf8Info("L" + className.replace('.', '/') + ";"), 0);
            for (int i = 0; i < vars.length; i++) {
                lva.addEntry(0, len,
                    cp.addUtf8Info(vars[i][0]),
                    cp.addUtf8Info(vars[i][1]), i + 1);
            }
            code.getAttributes().add(lva);
        } catch (Exception e) {
            log.warn("Failed to add LocalVariableTable: {}", e.getMessage());
        }
    }

    /**
     * Compiles a hierarchy rule expression into a {@code BiFunction} class.
     *
     * <p>Flow: expression → {@link HierarchyRuleScriptParser#parse} (ANTLR4 AST)
     * → {@link #generateApplyMethod} (Java source) → Javassist compile → class load.
     * Property access (e.g., {@code u.name}) is mapped to getter calls
     * (e.g., {@code u.getName()}) via {@link #toGetter(String)}.
     * Equality comparisons use {@code java.util.Objects.equals()} for null safety.
     *
     * <p>If parsing or compilation fails, throws immediately (fail-fast at startup).
     *
     * @param ruleName   the rule name (e.g., "name", "short-name")
     * @param expression the rule expression string
     * @return a BiFunction that matches two Service objects
     */
    @SuppressWarnings("unchecked")
    public BiFunction<Service, Service, Boolean> compile(
            final String ruleName, final String expression) throws Exception {
        final HierarchyRuleModel model = HierarchyRuleScriptParser.parse(expression);
        final String saved = classNameHint;
        if (classNameHint == null) {
            classNameHint = ruleName;
        }
        final String className;
        try {
            className = makeClassName("HierarchyRule_");
        } finally {
            classNameHint = saved;
        }

        final CtClass ctClass = classPool.makeClass(className);
        ctClass.addInterface(classPool.get("java.util.function.BiFunction"));

        ctClass.addConstructor(CtNewConstructor.defaultConstructor(ctClass));

        final String applyBody = generateApplyMethod(model);

        if (log.isDebugEnabled()) {
            log.debug("Hierarchy compile [{}] AST: {}", ruleName, model);
            log.debug("Hierarchy compile [{}] apply():\n{}", ruleName, applyBody);
        }

        final javassist.CtMethod applyMethod = CtNewMethod.make(applyBody, ctClass);
        ctClass.addMethod(applyMethod);
        addLineNumberTable(applyMethod, 3);
        final String svcDesc = "Lorg/apache/skywalking/oap/server/core/query/type/Service;";
        addLocalVariableTable(applyMethod, className, new String[][]{
            {"arg0", "Ljava/lang/Object;"},
            {"arg1", "Ljava/lang/Object;"},
            {model.getUpperParam(), svcDesc},
            {model.getLowerParam(), svcDesc}
        });

        setSourceFile(ctClass, formatSourceFileName(ruleName));
        writeClassFile(ctClass);
        final Class<?> clazz = ctClass.toClass(HierarchyRulePackageHolder.class);
        ctClass.detach();
        return (BiFunction<Service, Service, Boolean>) clazz.getDeclaredConstructor().newInstance();
    }

    private String generateApplyMethod(final HierarchyRuleModel model) {
        final StringBuilder sb = new StringBuilder();
        sb.append("public Object apply(Object arg0, Object arg1) {\n");
        sb.append("  org.apache.skywalking.oap.server.core.query.type.Service ");
        sb.append(model.getUpperParam()).append(" = (org.apache.skywalking.oap.server.core.query.type.Service) arg0;\n");
        sb.append("  org.apache.skywalking.oap.server.core.query.type.Service ");
        sb.append(model.getLowerParam()).append(" = (org.apache.skywalking.oap.server.core.query.type.Service) arg1;\n");

        generateRuleBody(sb, model.getBody());

        sb.append("}\n");
        return sb.toString();
    }

    private void generateRuleBody(final StringBuilder sb,
                                  final HierarchyRuleModel.RuleBody body) {
        if (body instanceof HierarchyRuleModel.SimpleComparison) {
            final HierarchyRuleModel.SimpleComparison cmp =
                (HierarchyRuleModel.SimpleComparison) body;
            sb.append("  return Boolean.valueOf(");
            generateComparison(sb, cmp.getLeft(), cmp.getOp(), cmp.getRight());
            sb.append(");\n");
        } else if (body instanceof HierarchyRuleModel.BlockBody) {
            final HierarchyRuleModel.BlockBody block = (HierarchyRuleModel.BlockBody) body;
            for (final HierarchyRuleModel.Statement stmt : block.getStatements()) {
                generateStatement(sb, stmt);
            }
        }
    }

    private void generateStatement(final StringBuilder sb,
                                   final HierarchyRuleModel.Statement stmt) {
        if (stmt instanceof HierarchyRuleModel.IfStatement) {
            generateIfStatement(sb, (HierarchyRuleModel.IfStatement) stmt);
        } else if (stmt instanceof HierarchyRuleModel.ReturnStatement) {
            generateReturnStatement(sb, (HierarchyRuleModel.ReturnStatement) stmt);
        }
    }

    private void generateIfStatement(final StringBuilder sb,
                                     final HierarchyRuleModel.IfStatement ifStmt) {
        sb.append("  if (");
        generateCondition(sb, ifStmt.getCondition());
        sb.append(") {\n");
        for (final HierarchyRuleModel.Statement s : ifStmt.getThenBranch()) {
            generateStatement(sb, s);
        }
        sb.append("  }\n");
        if (ifStmt.getElseBranch() != null && !ifStmt.getElseBranch().isEmpty()) {
            sb.append("  else {\n");
            for (final HierarchyRuleModel.Statement s : ifStmt.getElseBranch()) {
                generateStatement(sb, s);
            }
            sb.append("  }\n");
        }
    }

    private void generateReturnStatement(final StringBuilder sb,
                                         final HierarchyRuleModel.ReturnStatement retStmt) {
        final HierarchyRuleModel.Expr expr = retStmt.getValue();
        if (expr instanceof HierarchyRuleModel.SimpleComparison) {
            final HierarchyRuleModel.SimpleComparison cmp =
                (HierarchyRuleModel.SimpleComparison) expr;
            sb.append("  return Boolean.valueOf(");
            generateComparison(sb, cmp.getLeft(), cmp.getOp(), cmp.getRight());
            sb.append(");\n");
        } else if (expr instanceof HierarchyRuleModel.BoolLiteralExpr) {
            sb.append("  return Boolean.valueOf(")
              .append(((HierarchyRuleModel.BoolLiteralExpr) expr).isValue())
              .append(");\n");
        } else {
            sb.append("  return Boolean.valueOf(");
            generateExpr(sb, expr);
            sb.append(" != null);\n");
        }
    }

    private void generateComparison(final StringBuilder sb,
                                    final HierarchyRuleModel.Expr left,
                                    final HierarchyRuleModel.CompareOp op,
                                    final HierarchyRuleModel.Expr right) {
        switch (op) {
            case EQ:
                sb.append("java.util.Objects.equals(");
                generateExpr(sb, left);
                sb.append(", ");
                generateExpr(sb, right);
                sb.append(")");
                break;
            case NEQ:
                sb.append("!java.util.Objects.equals(");
                generateExpr(sb, left);
                sb.append(", ");
                generateExpr(sb, right);
                sb.append(")");
                break;
            case GT:
                generateExpr(sb, left);
                sb.append(" > ");
                generateExpr(sb, right);
                break;
            case LT:
                generateExpr(sb, left);
                sb.append(" < ");
                generateExpr(sb, right);
                break;
            case GTE:
                generateExpr(sb, left);
                sb.append(" >= ");
                generateExpr(sb, right);
                break;
            case LTE:
                generateExpr(sb, left);
                sb.append(" <= ");
                generateExpr(sb, right);
                break;
            default:
                throw new IllegalArgumentException("Unsupported comparison op: " + op);
        }
    }

    private void generateCondition(final StringBuilder sb,
                                   final HierarchyRuleModel.Condition cond) {
        if (cond instanceof HierarchyRuleModel.ComparisonCondition) {
            final HierarchyRuleModel.ComparisonCondition cc =
                (HierarchyRuleModel.ComparisonCondition) cond;
            generateComparison(sb, cc.getLeft(), cc.getOp(), cc.getRight());
        } else if (cond instanceof HierarchyRuleModel.LogicalCondition) {
            final HierarchyRuleModel.LogicalCondition lc =
                (HierarchyRuleModel.LogicalCondition) cond;
            sb.append("(");
            generateCondition(sb, lc.getLeft());
            sb.append(lc.getOp() == HierarchyRuleModel.LogicalOp.AND ? " && " : " || ");
            generateCondition(sb, lc.getRight());
            sb.append(")");
        } else if (cond instanceof HierarchyRuleModel.NotCondition) {
            sb.append("!(");
            generateCondition(sb, ((HierarchyRuleModel.NotCondition) cond).getInner());
            sb.append(")");
        } else if (cond instanceof HierarchyRuleModel.ExprCondition) {
            generateExpr(sb, ((HierarchyRuleModel.ExprCondition) cond).getExpr());
        }
    }

    private void generateExpr(final StringBuilder sb,
                              final HierarchyRuleModel.Expr expr) {
        if (expr instanceof HierarchyRuleModel.MethodChainExpr) {
            generateMethodChainExpr(sb, (HierarchyRuleModel.MethodChainExpr) expr);
        } else if (expr instanceof HierarchyRuleModel.StringLiteralExpr) {
            sb.append('"')
              .append(escapeJava(((HierarchyRuleModel.StringLiteralExpr) expr).getValue()))
              .append('"');
        } else if (expr instanceof HierarchyRuleModel.NumberLiteralExpr) {
            sb.append(((HierarchyRuleModel.NumberLiteralExpr) expr).getValue());
        } else if (expr instanceof HierarchyRuleModel.BoolLiteralExpr) {
            sb.append(((HierarchyRuleModel.BoolLiteralExpr) expr).isValue());
        } else if (expr instanceof HierarchyRuleModel.BinaryExpr) {
            final HierarchyRuleModel.BinaryExpr bin = (HierarchyRuleModel.BinaryExpr) expr;
            generateExpr(sb, bin.getLeft());
            sb.append(bin.getOp() == HierarchyRuleModel.ArithmeticOp.ADD ? " + " : " - ");
            generateExpr(sb, bin.getRight());
        } else if (expr instanceof HierarchyRuleModel.SimpleComparison) {
            final HierarchyRuleModel.SimpleComparison cmp =
                (HierarchyRuleModel.SimpleComparison) expr;
            generateComparison(sb, cmp.getLeft(), cmp.getOp(), cmp.getRight());
        }
    }

    private void generateMethodChainExpr(final StringBuilder sb,
                                         final HierarchyRuleModel.MethodChainExpr expr) {
        sb.append(expr.getTarget());
        for (final HierarchyRuleModel.ChainSegment seg : expr.getSegments()) {
            sb.append('.');
            if (seg instanceof HierarchyRuleModel.FieldAccess) {
                final String fieldName = ((HierarchyRuleModel.FieldAccess) seg).getName();
                sb.append(toGetter(fieldName)).append("()");
            } else if (seg instanceof HierarchyRuleModel.MethodCallSegment) {
                final HierarchyRuleModel.MethodCallSegment mc =
                    (HierarchyRuleModel.MethodCallSegment) seg;
                sb.append(mc.getName()).append('(');
                final List<HierarchyRuleModel.Expr> args = mc.getArguments();
                for (int i = 0; i < args.size(); i++) {
                    if (i > 0) {
                        sb.append(", ");
                    }
                    generateExpr(sb, args.get(i));
                }
                sb.append(')');
            }
        }
    }

    /**
     * Maps a field name in rule expressions to the corresponding getter method
     * on {@link Service}. Known fields ({@code name} → {@code getName},
     * {@code shortName} → {@code getShortName}) are hard-coded for clarity;
     * unknown fields fall back to JavaBean convention ({@code foo} → {@code getFoo}).
     * If the getter does not exist on {@link Service}, Javassist compilation will
     * fail at startup with a clear error.
     */
    private static String toGetter(final String fieldName) {
        if ("name".equals(fieldName)) {
            return "getName";
        } else if ("shortName".equals(fieldName)) {
            return "getShortName";
        }
        return "get" + Character.toUpperCase(fieldName.charAt(0)) + fieldName.substring(1);
    }

    private static String escapeJava(final String s) {
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    /**
     * Generates the Java source body of the apply method for debugging/testing.
     */
    public String generateSource(final String expression) {
        final HierarchyRuleModel model = HierarchyRuleScriptParser.parse(expression);
        return generateApplyMethod(model);
    }
}
