# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.14 AS builder

ARG COMMIT_HASH=827f3a45e44cb2a64f874ff17d9eb454a680d08f
ARG SATELLITE_CODE=${COMMIT_HASH}.tar.gz
ARG SATELLITE_CODE_URL=https://github.com/apache/skywalking-satellite/archive/${SATELLITE_CODE}

ENV CGO_ENABLED=0

WORKDIR /skywalking-satellite

ADD ${SATELLITE_CODE_URL} .
RUN tar -xf ${SATELLITE_CODE} --strip 1
RUN rm ${SATELLITE_CODE}

RUN make linux

FROM alpine:3.10

COPY --from=builder /skywalking-satellite/bin/skywalking-satellite-latest-linux-amd64 /sw-satellite

ENTRYPOINT ["/sw-satellite"]